### ISSUE TITLE
Any plans on the next release?

### ISSUE THREAD

**Issue by DeVon30135** [DeviceFarmer/stf#128]
We've recently started switching our cloud device testing solution to STF and it's been incredibly helpful. I'm curious if you have any plans on creating a new release branch any time soon? I've seen most items recommend pulling the latest build, but wanted to know your thoughts on creating a dedicated release plan. I, personally, am excited for Android 11 support (#109) and thought it would be a great feature for a new release.

**Comment by koral--** [comment]
It is not yet decided when next version will be released. I'll get back here ASAP.

**Comment by koral--** [comment]
Version 3.5.0 has been released.
