### ISSUE TITLE
AAB installation fails when /tmp is on different mountpoint than /data

### ISSUE THREAD

**Issue by koral--** [DeviceFarmer/stf#136]
```
Error: EXDEV: cross-device link not permitted, rename '/tmp/universal.apk' -> '/data/upload_2157f12010a7da382eda71b6e250ef54'
at Object.fs.renameSync (fs.js:766:18)
```
CC @nghiaviminh since it was added here:
https://github.com/DeviceFarmer/stf/pull/103/files#diff-246ebba554a261ed72c1704d955a9d89fbf9067caeeaf781426d0f9d32403aeaR99
what do you think ?

One of the ideas I have is to use copy & remove instead of renaming. Or maybe is there something better in `fs` package for that?

**Comment by nghiaviminh** [comment]
I have submitted new PR with the fix for this bug. Using fs.copyFileSync() instead of fs.renameSync() solved this issue.
