### ISSUE TITLE
Gulp 4 : Error “The following tasks did not complete: build, clean, <anonymous> Did you forget to signal async completion?”

### ISSUE THREAD

**Issue by udaykittu** [DeviceFarmer/stf#140]
Stf 3.5.0

Upgraded Gulp version to 4 & error is occurring

Steps:
1. Update the gulp packages to 4.x.x
 Expected: 
2. npm link should be a success

Error: The following tasks did not complete: build, clean, <anonymous> Did you forget to signal async completion?
`
var gulp = require('gulp')
var gutil = require('gulp-util')
var jsonlint = require('gulp-jsonlint')
var eslint = require('gulp-eslint')
var EslintCLIEngine = require('eslint').CLIEngine
var webpack = require('webpack')
var webpackConfig = require('./webpack.config').webpack
var webpackStatusConfig = require('./res/common/status/webpack.config')
var gettext = require('gulp-angular-gettext')
var pug = require('gulp-pug')
var del = require('del')
// var protractor = require('gulp-protractor')
var protractor = require('./res/test/e2e/helpers/gulp-protractor-adv')
var protractorConfig = './res/test/protractor.conf'
var karma = require('karma').server
var karmaConfig = '/res/test/karma.conf.js'
var stream = require('stream')
var run = require('gulp-run')

gulp.task('jsonlint', gulp.series(function() {
  return gulp.src([
      '.bowerrc'
    , '.yo-rc.json'
    , '*.json'
    ])
    .pipe(jsonlint())
    .pipe(jsonlint.reporter())
}))

// Try to use eslint-cli directly instead of eslint-gulp
// since it doesn't support cache yet
gulp.task('eslint', gulp.series(function() {
  return gulp.src([
      'lib/**/*.js'
    , 'res/**/*.js'
    , '!res/bower_components/**'
    , '*.js'
  ])
    // eslint() attaches the lint output to the "eslint" property
    // of the file object so it can be used by other modules.
    .pipe(eslint())
    // eslint.format() outputs the lint results to the console.
    // Alternatively use eslint.formatEach() (see Docs).
    .pipe(eslint.format())
    // To have the process exit with an error code (1) on
    // lint error, return the stream and pipe to failAfterError last.
    .pipe(eslint.failAfterError())
}))

gulp.task('eslint-cli', gulp.series(function(done) {
  var cli = new EslintCLIEngine({
    cache: true
  , fix: false
  })

  var report = cli.executeOnFiles([
    'lib/**/*.js'
    , 'res/app/**/*.js'
    , 'res/auth/**/*.js'
    , 'res/common/**/*.js'
    , 'res/test/**/*.js'
    , 'res/web_modules/**/*.js'
    , '*.js'
  ])
  var formatter = cli.getFormatter()
  console.log(formatter(report.results))

  if (report.errorCount > 0) {
    done(new gutil.PluginError('eslint-cli', new Error('ESLint error')))
  }
  else {
    done()
  }
}))

gulp.task('clean', gulp.series(function(cb) {
  del([
    './tmp'
    , './res/build'
    , '.eslintcache'
  ], cb)
}))

gulp.task('webpack:build', gulp.series(function(callback) {
  var myConfig = Object.create(webpackConfig)
  myConfig.plugins = myConfig.plugins.concat(
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify('production')
      }
    })
  )
  myConfig.devtool = false

  webpack(myConfig, function(err, stats) {
    if (err) {
      throw new gutil.PluginError('webpack:build', err)
    }

    gutil.log('[webpack:build]', stats.toString({
      colors: true
    }))

    // Save stats to a json file
    // Can be analyzed in http://webpack.github.io/analyse/
    fromString('stats.json', JSON.stringify(stats.toJson()))
      .pipe(gulp.dest('./tmp/'))

    callback()
  })
}))

gulp.task('lint', gulp.series('jsonlint', 'eslint-cli'))

gulp.task('run:checkversion', gulp.series(function() {
  gutil.log('Checking STF version...')
  return run('./bin/stf -V').exec()
}))
gulp.task('test', gulp.series('lint', 'run:checkversion'))
gulp.task('build', gulp.series('clean', 'webpack:build'))
gulp.task('karma_ci', gulp.series(function(done) {
  karma.start({
    configFile: path.join(__dirname, karmaConfig)
  , singleRun: true
  }, done)
}))

gulp.task('karma', gulp.series(function(done) {
  karma.start({
    configFile: path.join(__dirname, karmaConfig)
  }, done)
}))

if (gutil.env.multi) {
  protractorConfig = './res/test/protractor-multi.conf'
}
else if (gutil.env.appium) {
  protractorConfig = './res/test/protractor-appium.conf'
}

gulp.task('webdriver-update', protractor.webdriverUpdate)
gulp.task('webdriver-standalone', protractor.webdriverStandalone)
gulp.task('protractor-explorer', gulp.series(function(callback) {
  return protractor.protractorExplorer({
    url: require(protractorConfig).config.baseUrl
  }, callback)
}))

gulp.task('protractor', gulp.series('webdriver-update', function(callback) {
   return gulp.src(['./res/test/e2e/**/*.js'])
    .pipe(protractor.protractor({
      configFile: protractorConfig
    , debug: gutil.env.debug
    , suite: gutil.env.suite
    }))
    .on('error', function(e) {
      console.log(e)

      /* eslint no-console: 0 */
    })
    .on('end', callback)
}))

// For piping strings
function fromString(filename, string) {
  var src = new stream.Readable({objectMode: true})
  src._read = function() {
    this.push(new gutil.File({
      cwd: ''
    , base: ''
    , path: filename
    , contents: new Buffer(string)
    }))
    this.push(null)
  }
  return src
}

// For production

gulp.task('webpack:others', gulp.series(function(callback) {
  var myConfig = Object.create(webpackStatusConfig)
  myConfig.plugins = myConfig.plugins.concat(
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify('production')
      }
    })
  )
  myConfig.devtool = false

  webpack(myConfig, function(err, stats) {
    if (err) {
      throw new gutil.PluginError('webpack:others', err)
    }

    gutil.log('[webpack:others]', stats.toString({
      colors: true
    }))
    callback()
  })
}))

gulp.task('pug', gulp.series(function() {
  return gulp.src([
      './res/**/*.pug'
    , '!./res/bower_components/**'
    ])
    .pipe(pug({
      locals: {
        // So res/views/docs.pug doesn't complain
        markdownFile: {
          parseContent: function() {
          }
        }
      }
    }))
    .pipe(gulp.dest('./tmp/html/'))
}))

gulp.task('translate:extract', gulp.series('pug', function() {
  return gulp.src([
      './tmp/html/**/*.html'
    , './res/**/*.js'
    , '!./res/bower_components/**'
    , '!./res/build/**'
    ])
    .pipe(gettext.extract('stf.pot'))
    .pipe(gulp.dest('./res/common/lang/po/'))
}))

gulp.task('translate:compile', gulp.series(function() {
  return gulp.src('./res/common/lang/po/**/*.po')
    .pipe(gettext.compile({
      format: 'json'
    }))
    .pipe(gulp.dest('./res/common/lang/translations/'))
}))

gulp.task('translate:push', gulp.series(function() {
  gutil.log('Pushing translation source to Transifex...')
  return run('tx push -s').exec()
}))

gulp.task('translate:pull', gulp.series(function() {
  gutil.log('Pulling translations from Transifex...')
  return run('tx pull').exec()
}))

gulp.task('translate', gulp.series(
  'translate:extract'
, 'translate:push'
, 'translate:pull'
, 'translate:compile'
))`

**Comment by denis99999** [comment]
@udaykittu , as specified in the `package.json`, the `gulp `versions 4.x.x are currently not supported

**Comment by udaykittu** [comment]
Thanks @denis99999 

I have reverted the changes for gulp packages to the original one from the git hub. 

After reverting the changes, below error is being shown while executing `npm link`

npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> @devicefarmer/stf@3.5.0 prepublish /Users/udaykumarraju.s/Desktop/STF/openstf-master
> bower install && not-in-install && gulp build || in-install

fs.js:45
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:45:5
    at req_ (/Users/udaykumarraju.s/Desktop/STF/openstf-master/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/udaykumarraju.s/Desktop/STF/openstf-master/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/udaykumarraju.s/Desktop/STF/openstf-master/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @devicefarmer/stf@3.5.0 prepublish: `bower install && not-in-install && gulp build || in-install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @devicefarmer/stf@3.5.0 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

Kindly help in fixing the issue

**Comment by udaykittu** [comment]
Issue resolved on downgrading node to v8
