### ISSUE TITLE
Feature Request: pop-out / full screen device view

### ISSUE THREAD

**Issue by lanrat** [DeviceFarmer/stf#146]
**Describe the solution you'd like**
It would be nice if the remove view could be made larger or allowed opening just the interactive remove view in a separate window to make interacting from devices on smaller screens easier.

**Describe alternatives you've considered**
Browser zoom works a little, but does not work well with all the additional controls STF has on the right of the control panel.

**Comment by swijk** [comment]
I believe this feature already exists if you shift + click a device.

**Comment by koral--** [comment]
Good catch!
Thanks, so I'm closing the issue.
