### ISSUE TITLE
ERR! OMG CMake executable is not found.

### ISSUE THREAD

**Issue by arhanechka** [DeviceFarmer/stf#169]
during npm install -g @devicefarmer/stf I have an error
prebuild-install WARN install No prebuilt binaries found (target=14.13.1 runtime=node arch=x64 libc= platform=darwin)
[
  '/usr/local/Cellar/node/14.13.1_1/bin/node',
  '/usr/local/lib/node_modules/@devicefarmer/stf/node_modules/.bin/cmake-js',
  'compile',
  '--target',
  'jpegturbo'
]
info TOOL Using Unix Makefiles generator.
info TOOL Building only the jpegturbo target, as specified from the command line.
info REP Build has been failed, trying to do a full rebuild.
ERR! OMG CMake executable is not found. Please use your system's package manager to install it, or you can get installers from there: http://cmake.org.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @julusian/jpeg-turbo@0.5.6 install: `prebuild-install || cmake-js compile --target jpegturbo`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @julusian/jpeg-turbo@0.5.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
pls help

**Comment by jachstet-sea** [comment]
Well, just do what the build errors recommends: `Please use your system's package manager to install it, or you can get installers from there: http://cmake.org.`

**Comment by koral--** [comment]
I think we can add cmake to the requirements list in the Readme.
