### ISSUE TITLE
I'm Not Worthy..Lol..

### ISSUE THREAD

**Issue by EntroFlux** [DeviceFarmer/stf#211]
I am sure I am at the back of a long line for fans..I accidentally stumbled on your repo.....I do no think I  am capable of putting into words how  impressed I am..

umm

I wanna play..lol

seriously..

I am a developer of sorts....Though I cannot code my way out of a wet paper bag...

I understand the logic...assembling code into a working build is not my forte..

this is the part where you ask what use I would be..

 You  lads have the android bits well in hand.....

seems iOS is  the current challenge...

 I work primarily with iOS 

Systems are my Jam...I have  a fully functional test bed...every scrap of infrastructure you  could possibly need.

100+ iOS devices
Bonded WAN Fiber/Cable
Servers.
Mac's
Multiple Domains
Industrial USB network 
Respectable collection  of licenses that claim I am an actual developer..

I play nice with others && read log files like Jesus is writing them to me..

I am not asking for anything other than to play with your toys...as that is my outlook on the things we all create..

I find it beyond doubt that I will be an asset to the development process if for nothing more than as a tester who provides exceptional  && accurate feedback...I can break nearly anything

Do Ya'll have a chat I can join?

I might add that I am from the US...Deep South......Alabama to be precise.....if nothing else the addition of the only existing Redneck Systems Architect in existence that I am aware of...would add some spice to the team...

I am few hours out from leaving on Holiday...so I will  not be available for anything more than discussion for the next ten days..

Have a think about it and let me know..

peas..Flux

**Comment by koral--** [comment]
Here is the slack: https://join.slack.com/t/devicefarmer/shared_invite/zt-f2wyd8n4-M81Gfx3nT19VmqdD8j3GSQ
