### ISSUE TITLE
Problem during installation, HELP

### ISSUE THREAD

**Issue by ababushkin-bscmsc** [DeviceFarmer/stf#219]
I can't install via Docker and cleanly to the server.
**error:**
bower ng-context-menu#~1.0.5                                                 ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/AdiDahan/ng-context-menu.git", exit code of #128 remote: Invalid username or password. fatal: Authentication failed for 'https://github.com/AdiDahan/ng-context-menu.git/'

Additional error details:
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/AdiDahan/ng-context-menu.git/'

There is no such repository

Please help me

**Comment by sudhalucky** [comment]
Same issue with me....

**Comment by shridharkabbur** [comment]
Yes, i too noticed. The repository is missing now.. I mean no public repository.

**Comment by nghiaviminh** [comment]
In bower.json, change "ng-context-menu" from "AdiDahan/ng-context-menu#~1.0.5" to "swimlane/ng-context-menu#~1.0.1". I used Wayback machine to look at 'https://github.com/AdiDahan/ng-context-menu.git/' and I found the original owner was ianwalter, "swimlane/ng-context-menu" claims that it was originated from "ianwalter/ng-context-menu" so I give it a shot and it works

**Comment by shridharkabbur** [comment]
However i have copy of 'https://github.com/AdiDahan/ng-context-menu.git/'  repo. Attaching the dist folder of it.
[dist.zip](https://github.com/DeviceFarmer/stf/files/6278745/dist.zip)
