### ISSUE TITLE
ng-context-menu missing from github

### ISSUE THREAD

**Issue by pafels** [DeviceFarmer/stf#255]
I'm trying to install stf (bower install devicefarmer/stf) but it seems like one of the dependencies is missing from github:

Password for 'https://github.com': 
bower ng-context-menu#~1.0.5                                                 ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/AdiDahan/ng-context-menu.git", exit code of #128 remote: Repository not found. fatal: Authentication failed for 'https://github.com/AdiDahan/ng-context-menu.git/'

Additional error details:
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/AdiDahan/ng-context-menu.git/'

**Comment by koral--** [comment]
It was already fixed https://github.com/DeviceFarmer/stf/commit/38cb66b1bd0917344481f8e74f0777935baf6bed
