### ISSUE TITLE
can you provide minicap.so for Android 11? Thanks very much

### ISSUE THREAD

**Issue by pxrgod** [DeviceFarmer/stf#258]

**Comment by koral--** [comment]
It is present in [@devicefarmer/minicap-prebuilt](https://www.npmjs.com/package/@devicefarmer/minicap-prebuilt) npm package. You can extract so files from there.

**Comment by pxrgod** [comment]
> It is present in [@devicefarmer/minicap-prebuilt](https://www.npmjs.com/package/@devicefarmer/minicap-prebuilt) npm package. You can extract so files from there.

currently, it only support android version 10 and lower，please check it! Thanks

android-29 for android 10

**Comment by pxrgod** [comment]
> It is present in [@devicefarmer/minicap-prebuilt](https://www.npmjs.com/package/@devicefarmer/minicap-prebuilt) npm package. You can extract so files from there.

I am so sorry, I can find this minicap.so for android 11. thanks.
