### ISSUE TITLE
Nginx Configuration for the docker based setup

### ISSUE THREAD

**Issue by ommikadam** [DeviceFarmer/stf#266]
Hi,

I've done setup of STF with the docker-compose.yml file and changed the public IP as my private IP in the parameter of docker compose.
Iam able to work locally from my network but how to make it public via nginx with domain name can anyone help. As I forwarded the port 7100 but its not working.

pls help

**Comment by jay0129** [comment]
At first, you need a public IP to make your service public.

**Comment by ommikadam** [comment]
its sorted thanks
