### ISSUE TITLE
Close browser tab while using device, device won't return to available (still Busy)

### ISSUE THREAD

**Issue by nhunh585** [DeviceFarmer/stf#38]
While using the device, If I close browser or close stf tab, the device won't return to available (still Busy)

**Comment by jachstet-sea** [comment]
Are you still connected to the device via ADB?

**Comment by nhunh585** [comment]
No I'm just using device by browser, not using abd.

**Comment by denis99999** [comment]
@nhunh585 ,
It is a normal behavior, not an issue (e.g. the device may be used through API and/or ADB by a script test or through another browser opened on it, etc.), conversely it would be an issue to make available the device on such GUI event.
The device should be made available after the timeout you fixed (i.e. `--group-timeout` parameter), or on an explicit action using API or GUI.

**Comment by brian-leidos** [comment]
You could go to Admin mode so that you can override a device being busy:
Click the yellow person icon and press:
Up Up Down Down Left Right Left Right Enter

**Comment by koral--** [comment]
Closing as answer is already provided.
