### ISSUE TITLE
Please tell me, what is minicap.apk for？

### ISSUE THREAD

**Issue by csdaa** [DeviceFarmer/stf#414]
Please tell me, what is minicap.apk for？

**Comment by denis99999** [comment]
@csdaa ,

`Minicap `is used for screen streaming and screen capturing of Android devices.
Regards.

**Comment by csdaa** [comment]
> @csdaa ,
> 
> `Minicap `is used for screen streaming and screen capturing of Android devices. Regards.

think you very much
