### ISSUE TITLE
Can this solution be used to access remote Android devices (Smart TV's) over the internet?

### ISSUE THREAD

**Issue by acrolink** [DeviceFarmer/stf#42]
My question, is this solution suitable to access and control remotely Android devices over the internet (unattended any time). If so, what are the special requirements? opening ports on router where the device is installed?

Or does it work only by providing the IP address of the STF server and configuring it on the to be controlled device?

**Comment by koral--** [comment]
You can use `allow-remote` option in provider unit and connect those devices via remote adb to adb unit.
There is no special requirements enforced by STF itself.
You need to follow the standard requirements for remote adb connections: https://developer.android.com/studio/command-line/adb#wireless
Among the others you need to open the port on firewall.

**Comment by gam2046** [comment]
> You can use `allow-remote` option in provider unit and connect those devices via remote adb to adb unit.
> There is no special requirements enforced by STF itself.
> You need to follow the standard requirements for remote adb connections: https://developer.android.com/studio/command-line/adb#wireless
> Among the others you need to open the port on firewall.

Is there any sample? For example, I want to connect a remote Android device (10.10.10.100:5555) through stf. What should I do?

**Comment by APOSHAml** [comment]
I have the same question
