### ISSUE TITLE
Need to update NodeJS to > 8.x

### ISSUE THREAD

**Issue by Dr-Desty-Nova** [DeviceFarmer/stf#441]
Current published docker images are still based on NodeJS 8.x.

Unfortunately, Letsencrypt recently changed their PKI chain so it is signed by another CA. NodeJS 8.x has [embedded list of CAs it trusts](https://github.com/nodejs/node/blob/master/src/node_root_certs.h), and it doesn't have this new chain.

So in case all services are available through https, `apk` and `image` plugins can't work with STF storage api, and provider service can't push uploaded apk to the device, showing "Certificate expired" error.

**Comment by denis99999** [comment]
@Dr-Desty-Nova ,

From my side it works fine with `letsencrypt` using `nginx` as reverse proxy according to the example described in the `DEPLOYMENT.md` document, either through the UI or through the API using `swaggerUI`.

Have you implemented an `STF `deployment that highlights the problem you are indicating? If so, please provide details by following the recommended outcome model.

Regards.

**Comment by Kaned1as** [comment]
@denis99999 have you tried uploading apks through the web interface? Does it work for you?

**Comment by Dr-Desty-Nova** [comment]
Sounds good, I will recheck soon. Closing, will reopen if encounter any issues.
