### ISSUE TITLE
Release new version of Docker image.

### ISSUE THREAD

**Issue by rbprogrammer** [DeviceFarmer/stf#447]
**Is your feature request related to a problem? Please describe.**

The newest tagged versioned [devicefarmer/stf](https://hub.docker.com/r/devicefarmer/stf) on DockerHub is `3.5.0`.  However this will not work when testing with devices running Android 12 (API 31) and up.  Device Farmer version 3.5.0 has minicap-prebuilt with binaries only up to API 30.

**Describe the solution you'd like**

Would someone be able to update the `Dockerfile` (possibly so it extends from a newer base image of an LTS version of Ubuntu) and publish the new image to [Docker Hub](https://hub.docker.com/u/devicefarmer).  The most recent version of Device Farmer STF is 3.6.1, per the [package.json](https://github.com/DeviceFarmer/stf/blob/master/package.json).  This version should suffice, but I need it containerized.

**Describe alternatives you've considered**

I have considered using the current version of the `latest` tag, however it's conventionally not the right approach since you can never really know what verison of the software is when using a Docker `latest` tag.

**Additional context**

Additionally, I see nearly identical errors as #150, but with Android 12 / API 31 messages.

**Comment by koral--** [comment]
Good catch!
Will fix CI pipeline for dockerhub ASAP.

**Comment by koral--** [comment]
Version 3.6.1 is now on dockerhub.
Thanks for the report.

**Comment by rbprogrammer** [comment]
Posting update for posterity purposes...

Doing a little bit of digging, I believe the issue is less so with [DeviceFarmer/stf](https://github.com/DeviceFarmer/stf) and more so with [DeviceFarmer/minicap](https://github.com/DeviceFarmer/minicap).  The [@devicefarmer/minicap-prebuilt](https://www.npmjs.com/package/@devicefarmer/minicap-prebuilt) package v2.7.1 itself does not include `minicap.so` files for anything greater than `android-30` for any of the supported architectures.

There already appears to be a handful of Android-12 / API-31 tickets created:

* https://github.com/DeviceFarmer/minicap/issues?q=is%3Aissue+android+12+31
