### ISSUE TITLE
ldap is working?

### ISSUE THREAD

**Issue by KraMorK** [DeviceFarmer/stf#465]
**What is the issue or idea you have?**
issue
**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
full server
**Please provide the steps to reproduce the issue.**
i started the server from such a docker compose file:
https://pastebin.com/Sexw9mrz
everything works, but I would like to use ldap for authorization on the service
    environment:
      - TZ='Azia/Tomsk'
      - RETHINKDB_PORT_28015_TCP=tcp://rethinkdb:28015
      - STF_ADMIN_EMAIL=admin@example.com
      - STF_ADMIN_NAME=admin
      - LDAP-URL='ldap://secret.local'
      - PORT=389
      - LDAP_USERNAME_FIELD=mail
      - LDAP_BIND_DN='CN=ldap_agent,CN=Users,DC=secret,DC=local'
      - LDAP_BIND_CREDENTIALS=secretpassword
      - LDAP_SEARCH_DN='OU=users,OU=secret,DC=secret,DC=local'
      - LDAP_SEARCH_CLASS=user
but the application ignores them
I also tried, based on this problem https://github.com/openstf/stf/issues/908, to create 1 more container with an application in which the stf auth-ldap command will be launched, basically the application registered --auth-url, it didn't work either. how to set up integration with LDAP?
**What is the expected behavior?**
ldap auth is working
**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

**Please run `stf doctor` and paste the output here.**
stf@a1f80bf0246f:/app$ stf doctor
2022-03-11T07:35:01.618Z INF/cli:doctor 327 [*] OS Arch: x64
2022-03-11T07:35:01.620Z INF/cli:doctor 327 [*] OS Platform: linux
2022-03-11T07:35:01.620Z INF/cli:doctor 327 [*] OS Platform: 5.4.0-100-generic
2022-03-11T07:35:01.620Z INF/cli:doctor 327 [*] Using Node 8.9.3
2022-03-11T07:35:01.633Z INF/cli:doctor 327 [*] Using ZeroMQ 4.1.4
2022-03-11T07:35:01.649Z ERR/cli:doctor 327 [*] RethinkDB is not installed (`rethinkdb` is missing)
2022-03-11T07:35:01.649Z ERR/cli:doctor 327 [*] ProtoBuf is not installed (`protoc` is missing)
2022-03-11T07:35:01.649Z ERR/cli:doctor 327 [*] ADB is not installed (`adb` is missing)
2022-03-11T07:35:01.668Z INF/cli:doctor 327 [*] Using GraphicsMagick 1.3.23

**Comment by denis99999** [comment]
@KraMorK ,

Looking at your docker compose file, I didn't see any ldap variables set or ldap options specified on the command line, I recommend adding them to the `stf local` command as follows depending on your ldap specification: `stf local --auth-type ldap --auth-options '["--ldap-url","ldap://secret.local","--ldap-search-dn","OU=users,OU=secret,DC=secret,DC=local","--ldap-bind-dn","CN=ldap_agent,CN=Users,DC=secret,DC=local","--ldap-bind-credentials","secretpassword","--ldap-search-class","user"]' ...`

And normally it will works!
Regards.

**Comment by KraMorK** [comment]
yes it worked, thanks
only i had to put -ldap-search-field instead of --ldap-search-class

**Comment by denis99999** [comment]
@KraMorK 

Either you have to add the `administrator` user to your LDAP database, or you have to recreate your `rethinkdb` database with an existing user in your LDAP database, for this last case you have first to erase your existing `rethinkdb` database, then you have to set the `STF_ADMIN_NAME` and `STF_ADMIN_EMAIL` environment variables as desired and as described at the `Running` section of the the README.md, after what you will be able to start your STF server recreating the `rethinkdb` database with the good admin name and email, then log in as the admin user.

Regards.

**Comment by KraMorK** [comment]
Made by 2 method, everything works. thanks a lot)
