### ISSUE TITLE
How to increase the timeout for stf

### ISSUE THREAD

**Issue by Jitu1888** [DeviceFarmer/stf#475]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Jitu1888** [comment]
I am getting the time-out pop up and the application is getting closed. After that Application is getting uninstalled. How do I increase the timeout for STF. Its really impacting the Automation

**Comment by denis99999** [comment]
@Jitu1888 ,

You can configure the timeout through the `--group-timeout` parameter.
regards.

**Comment by Jitu1888** [comment]
@denis99999 thanks for the reply.

I am running the STF using a bash script. Below is the command

#!/bin/bash

set +e

source ~/.bash_profile
source ~/.bashrc
source ~/.profile
source ~/.zshrc

node_version="8.16.1"

ip=$1
quality=$2

cmd="nvm use --delete-prefix v$node_version --silent &>/dev/null && export SCREEN_JPEG_QUALITY=$quality && stf local --public-ip $ip &> stf.log 2>&1 < /dev/null &"
echo "executing cmd => $cmd"
eval $cmd

disown


Can you please tell me where to add it

**Comment by denis99999** [comment]
@Jitu1888 ,

`stf local --group-timeout 36000 --public-ip ...`

PS: `36000 `stands for 10 hours, this is just an example, you can get the help on command line: `stf local --help`

**Comment by Jitu1888** [comment]
@denis99999 Thanks
