### ISSUE TITLE
I am starting a sprint to update STF to support Android 11/12

### ISSUE THREAD

**Issue by kjbaker-uk** [DeviceFarmer/stf#487]
Hello I really like STF and for a few years now I have been using it for Android 7 - 9 devices. I now have a need for Android 11-12 support. I have decided to allocate 2 weeks to do a mini sprint to see how far I can get it.

If anyone has any suggestions before I start trying to work out how this all works that would be great. I will also be sharing changes back.

Cheers

**Comment by denis99999** [comment]
@kjbaker-uk ,
STF now support Android 11/12+ using the latest version.
Regards.
