### ISSUE TITLE
stf:latest (3.6.2) breaks provider - adb.createClient is not a function

### ISSUE THREAD

**Issue by bushbrother** [DeviceFarmer/stf#518]
**What is the issue or idea you have?**
After doing a recent pull to latest version (3.6.2) the provider constantly restarts with error in log saying "adb.createClient is not a function"

**Please provide the steps to reproduce the issue.**
extract from docker-compose.yml

provider:
    image: devicefarmer/stf:latest
    restart: unless-stopped
    command: stf provider --name ${STATION_NAME} --connect-sub tcp://dev-triproxy:7250 --connect-push tcp://dev-triproxy:7270 --storage-url http://${PUBLIC_IP}/ --public-ip ${PUBLIC_IP} --heartbeat-interval 10000 --screen-ws-url-pattern "ws://${PUBLIC_IP}/d/nuc/<%= serial %>/<%= publicPort %>/" --adb-host adb --min-port 7400 --max-port 7700 --allow-remote
    ports:
      - 7400-7700:7400-7700
    depends_on:
      - adb
      - dev-triproxy
      - triproxy
      - storage-temp

**What is the expected behavior?**

container does not restart :)

changing the above to be "image: devicefarmer/stf:3.6.1" instead of "latest" resolves the issue.

**Comment by koral--** [comment]
It's actually a WiP but there was no corresponding issue yet.
Here is the branch when progress can be tracked. https://github.com/DeviceFarmer/stf/compare/master...DeviceFarmer:adbkit-invocations?expand=1

**Comment by bushbrother** [comment]
OK. Any way I can get a build that supports Android 12 without what was done 4 days ago? Does dockerhub hold a history?

**Comment by bushbrother** [comment]
Sorted it using sha256 of working image :)

**Comment by denis99999** [comment]
@koral-- is it not safe to downgrade to the `adbkit `version 2 ?

**Comment by bushbrother** [comment]
> @koral-- is it not safe to downgrade to the `adbkit `version 2 ?

As I am doing a pull using compose I am not sure how I would achieve this ...

**Comment by koral--** [comment]
I guess @denis99999 referred to my comment https://github.com/DeviceFarmer/stf/issues/518#issuecomment-1108610744 and asked whether it is safe to downgrade adbkit on the current master. Instead of changing dozens of places where it is used.
Yeah, I think it is a best way to go for now.

**Comment by koral--** [comment]
Version 3.6.4 is now released.

**Comment by denis99999** [comment]
> I guess @denis99999 referred to my comment [#518 (comment)](https://github.com/DeviceFarmer/stf/issues/518#issuecomment-1108610744) and asked whether it is safe to downgrade adbkit on the current master. Instead of changing dozens of places where it is used.
> Yeah, I think it is a best way to go for now.

I would say we should downgrade to adbkit v2

**Comment by koral--** [comment]
Yeah, that is exactly what I did.
I downgraded adbkit to v2 and deployed the release to a real farm to check if it actually works.
