### ISSUE TITLE
Cannot remove device out of existing group

### ISSUE THREAD

**Issue by ConfusedMerlin** [DeviceFarmer/stf#526]
**What is the issue or idea you have?**
We do have a couple of groups, each with associated users and devices. Right now, one of these devices should be relocated to another group. Which does not work.  

We get an error message on screen inside the browser, claiming that the server it too busy and that we should try again later. (see attached file)

Looking up the docker container logs reveals, that there are two errors happening inside the api container. First, there are ten failed attempts to do something, and a 503 on the DELETE call (see log section).

And the device stays there.

We did restart all docker-containers, but the error persists. 

<img width="905" alt="Bildschirmfoto 2022-05-09 um 09 16 52" src="https://user-images.githubusercontent.com/29836528/167359266-647f3ec2-907b-4e0c-b594-02757294dabd.png">

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
As far as I can tell, all devices in all groups are affected.

**Please provide the steps to reproduce the issue.**
As Admin user,
go to Settings,
select Groups,
select a group,
extend the associated devices list,
hit the little bin icon at the entry of the device to un-group,
receive an error message in browser (try again later, server too busy),
receive Log-Errors from api-container.

**What is the expected behavior?**
See the device getting un-grouped after hitting the bin-icon

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
the docker-compose logs? yes, from the api-container, each time I hit the bin-icon these two messages pop up

2022-05-09T05:44:49.887Z DBG/api:controllers:apiutil 1 [*] wrappedlockGroupByOwner() failed 10 times in a loop!

10.180.139.70 - - [09/May/2022:05:44:49 +0000] "DELETE /api/v1/devices/520336b2ec1383eb/groups/d23503d73002408489e0a7daa5692e22 HTTP/1.1" 503 73 "https://our.url.de/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.81 Safari/537.36"

**Please run `stf doctor` and paste the output here.**
from within the api container? That template is a bit unfit for docker users ;) 
So yes, of course most of the stuff is missing inside the api container. 

2022-05-09T07:15:22.667Z INF/cli:doctor 18 [*] OS Arch: x64
2022-05-09T07:15:22.669Z INF/cli:doctor 18 [*] OS Platform: linux
2022-05-09T07:15:22.669Z INF/cli:doctor 18 [*] OS Platform: 5.4.0-89-generic
2022-05-09T07:15:22.669Z INF/cli:doctor 18 [*] Using Node 8.9.3
2022-05-09T07:15:22.847Z INF/cli:doctor 18 [*] Using ZeroMQ 4.1.4
2022-05-09T07:15:22.858Z ERR/cli:doctor 18 [*] RethinkDB is not installed (`rethinkdb` is missing)
2022-05-09T07:15:22.859Z ERR/cli:doctor 18 [*] ProtoBuf is not installed (`protoc` is missing)
2022-05-09T07:15:22.859Z ERR/cli:doctor 18 [*] ADB is not installed (`adb` is missing)
2022-05-09T07:15:23.200Z INF/cli:doctor 18 [*] Using GraphicsMagick 1.3.23

**Additional Information**

I should probably mention that we do use a  server-node architecture. And that it does not matter, if we try to un-group phones from the server, or from one of the nodes. All showcase the same error, including the appearance of the log-messages in the servers api container

**Comment by denis99999** [comment]
@ConfusedMerlin , please provide more information about your runtime environment: docker-compose file, main OS, STF version, groups type (bookable, ...), etc.

**Comment by ConfusedMerlin** [comment]
On it...

**Version**: 3.6.1
**OS**: 18.04.1-Ubuntu
**Group Type: 
`Demo Device Pool
Identifier: d23503d73002408489e0a7daa5692e22 - Class: Standard - Devices: 4 - Users: 13 - Owner: administrator`
_is that the group information you are after?_
**docker-compose.yml**:
`version: '2'

volumes:
  rethinkdb:
  storage-temp:

networks:
  db:
  internal:
  ldap:

services:
  ldapservice:
    image: ourRepository/osixia/openldap:1.5.0
    volumes:
      - ./ldap/data:/var/lib/ldap
      - ./ldap/conf:/etc/ldap/slapd.d
    networks:
      ldap:
    restart: unless-stopped
    environment:
      - LDAP_BASE_DN=secret
      - LDAP_ORGANISATION=evenMoreSecret
      - LDAP_DOMAIN=mostlySecret
      - LDAP_ADMIN_PASSWORD=certainlyNotWelcome

  ldapadminservice:
    image: ourRepository/osixia/phpldapadmin:0.9.0
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldapservice
      - PHPLDAPADMIN_HTTPS=true
    networks:
      internal:
      ldap:
    restart: unless-stopped
    depends_on:
      - ldapservice   

  ldappss:
    image: ourRepository/ltbproject/self-service-password:latest
    volumes:
      - ./pss/pss.conf.php:/var/www/conf/config.inc.local.php
      - ./images/STF-512.png:/var/www/html/images/logo.png
      - ./pss/pss-hom.css:/var/www/html/css/self-service-password.css
      - ./pss/en.inc.php:/var/www/lang/en.inc.php
      - ./pss/de.inc.php:/var/www/lang/de.inc.php
      - ./pss/footer.tpl:/var/www/templates/footer.tpl
    restart: unless-stopped
    depends_on:
      - ldapservice  
    networks:
      internal:
      ldap:              
    environment:
      - LDAP_BIND_PWD=${LDAP_ADMIN_PASSWORD}

  nginx:
    build: nginx/
    volumes:
      - ./nginx/nginx-ssl.conf:/etc/nginx/nginx.conf:ro
      - /etc/ssl/certs/stf-1.crt:/etc/nginx/ssl/stf-1.crt:ro
      - /etc/ssl/private/stf-1.key:/etc/nginx/ssl/stf-1.key:ro
      - /etc/ssl/certs/stf-dhparam.pem:/etc/nginx/ssl/stf-dhparam.pem:ro
      - ./nginx/nginx-ssl.conf:/etc/nginx/templates/nginx.conf.devicefarm
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
      - auth
      - storage-plugin-apk
      - storage-plugin-image
      - storage-temp
      - websocket
      - api
    networks:
      internal:
    environment:
      - SERVER_NAME=${SERVER_NAME}

  nginx-storage:
    build: nginx/
    volumes:
      - ./nginx/nginx-storage.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    depends_on:
      - app
      - auth
      - storage-plugin-apk
      - storage-plugin-image
      - storage-temp
      - websocket
      - api
    networks:
      internal:

  adb:
    image: ourRepository/sorccu/adb:latest
    restart: unless-stopped
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
    networks:
      internal:

  rethinkdb:
    image: ourRepository/rethinkdb:2.4
    restart: unless-stopped
    volumes:
      - rethinkdb:/data
    ports:
      - 8080:8080
      - 28015:28015
    networks:
      db:

  rethinkdb-log:
    image: $IMAGE_STF
    restart: unless-stopped
    environment:
      - RETHINKDB_PORT_28015_TCP
      - SECRET
    command: stf log-rethinkdb --connect-sub tcp://triproxy:7150
    networks:
      internal:
      db:

  app:
    image: $IMAGE_STF 
    restart: unless-stopped
    environment:
      - RETHINKDB_PORT_28015_TCP
      - SECRET
    volumes:
#our pretty devision picture
      - ./images/STF-512.png:/app/res/common/logo/exports/STF-512.png
      - ./images/afa-128.png:/app/res/common/logo/exports/STF-128.png
      - ./images/STF-512.png:/app/res/build/e831b7164c8a65b849691bff62cdb160.png
    command: stf app --auth-url https://${HOSTNAME}/auth/ldap/ --websocket-url wss://${HOSTNAME}/ --port 3000
    depends_on:
      - rethinkdb
      - auth
      - websocket
    networks:
      internal:
      db:

  auth:
    image: $IMAGE_STF 
    restart: unless-stopped
    environment:
      - RETHINKDB_PORT_28015_TCP
      - SECRET
      - STF_AUTH_LDAP_LDAP_URL=ldap://ldapservice
      - STF_AUTH_LDAP_LDAP_SEARCH_DN=secret
      - STF_AUTH_LDAP_LDAP_SEARCH_FIELD=userid
      - STF_AUTH_LDAP_LDAP_BIND_DN=secret
      - STF_AUTH_LDAP_LDAP_BIND_CREDENTIALS=${LDAP_ADMIN_PASSWORD}
    command: stf auth-ldap --app-url https://${HOSTNAME}/ --port 3000  
    # command: stf auth-mock --app-url https://${PUBLIC_IP}/ --port 3000  
    depends_on:
      - rethinkdb
    networks:
      internal:
      db:
      ldap:

  processor:
    image: $IMAGE_STF 
    restart: unless-stopped
    environment:
      - RETHINKDB_PORT_28015_TCP
    command: stf processor --connect-app-dealer tcp://triproxy:7160 --connect-dev-dealer tcp://dev-triproxy:7260
    depends_on:
      - rethinkdb
      - triproxy
      - dev-triproxy
    networks:
      internal:
      db:

  triproxy:
    image: $IMAGE_STF 
    restart: unless-stopped
    command: stf triproxy app --bind-pub "tcp://*:7150" --bind-dealer "tcp://*:7160" --bind-pull "tcp://*:7170"
    ports:
      - 7150:7150
      - 7160:7160
      - 7170:7170
    networks:
      internal:

  dev-triproxy:
    image: $IMAGE_STF 
    restart: unless-stopped
    command: stf triproxy dev --bind-pub "tcp://*:7250" --bind-dealer "tcp://*:7260" --bind-pull "tcp://*:7270"
    ports:
      - 7250:7250
      - 7260:7260
      - 7270:7270
    networks:
      internal:

  migrate:
    image: $IMAGE_STF 
    environment:
      - RETHINKDB_PORT_28015_TCP
      - STF_ADMIN_NAME=$STF_ADMIN_NAME 
      - STF_ADMIN_EMAIL=$STF_ADMIN_EMAIL
    command: stf migrate
    depends_on:
      - rethinkdb
    networks:
      db:

  provider:
    image: $IMAGE_STF 
    restart: unless-stopped
    command: stf provider --name ${STATION_NAME} --connect-sub tcp://dev-triproxy:7250 --connect-push tcp://dev-triproxy:7270 --storage-url http://nginx-storage/ --public-ip ${HOSTNAME} --heartbeat-interval 10000 --screen-ws-url-pattern "wss://${HOSTNAME}/d/${STATION_NAME}/<%= serial %>/<%= publicPort %>/" --adb-host adb --min-port 7400 --max-port 7700 --allow-remote
    ports:
      - 7400-7700:7400-7700
    depends_on:
      - adb
      - dev-triproxy
      - triproxy
      - storage-temp
    networks:
      internal:

  reaper:
    image: $IMAGE_STF 
    restart: unless-stopped
    environment:
      - RETHINKDB_PORT_28015_TCP
    depends_on:
      - migrate
      - rethinkdb
      - dev-triproxy
      - triproxy
    command: stf reaper dev --connect-push tcp://dev-triproxy:7270 --connect-sub tcp://triproxy:7150 --heartbeat-timeout 30000
    networks:
      internal:
      db:

  storage-plugin-apk:
    image: $IMAGE_STF 
    restart: unless-stopped
    command: stf storage-plugin-apk --port 3000 --storage-url http://storage-temp:3000/
    depends_on:
      - storage-temp
    networks:
      internal:

  storage-plugin-image:
    image: $IMAGE_STF 
    restart: unless-stopped
    command: stf storage-plugin-image --port 3000 --storage-url http://storage-temp:3000/
    depends_on:
      - storage-temp
    networks:
      internal:

  storage-temp:
    build: storage-temp/
    restart: unless-stopped
    volumes:
      - storage-temp:/app/data
    command: stf storage-temp --port 3000 --save-dir /app/data
    ports:
      - 3000:3000
    networks:
      internal:

  websocket:
    image: $IMAGE_STF 
    restart: unless-stopped
    environment:
      - SECRET
      - RETHINKDB_PORT_28015_TCP
    command: stf websocket --port 3000 --storage-url http://storage-temp:3000/ --connect-sub tcp://triproxy:7150 --connect-push tcp://triproxy:7170
    depends_on:
      - migrate
      - rethinkdb
      - storage-temp
      - triproxy
      - dev-triproxy
    networks:
      internal:
      db:

  api:
    image: $IMAGE_STF 
    restart: unless-stopped
    environment:
      - SECRET
      - RETHINKDB_PORT_28015_TCP
    command: stf api --port 3000 --connect-sub tcp://triproxy:7150 --connect-push tcp://triproxy:7170 --connect-sub-dev tcp://dev-triproxy:7250 --connect-push-dev tcp://dev-triproxy:7270
    depends_on:
      - migrate
      - rethinkdb
      - triproxy
    networks:
      internal:
      db:

  groups-engine:
    image: $IMAGE_STF 
    restart: unless-stopped
    environment:
      - SECRET
      - RETHINKDB_PORT_28015_TCP
    command: stf groups-engine --connect-sub tcp://triproxy:7150 --connect-push tcp://triproxy:7170 --connect-sub-dev tcp://dev-triproxy:7250 --connect-push-dev tcp://dev-triproxy:7270
    depends_on:
      - migrate
      - rethinkdb
      - triproxy
      - dev-triproxy
    networks:
      internal:
      db:
`


Call for more if needed, I am fairly new to the whole devicefarming and fail to find good candidates for etc :(

**Comment by denis99999** [comment]
@ConfusedMerlin , 
I couldn't reproduce your issue with the same use case, I used a STF version `3.6.1` build `2e327b8b`, but not a `docker-compose` file to launch the containers, I noticed that in your `triproxy` and `dev-triproxy` entries you forget the '*' character in URL, try also to use a simpler configuration using a local one as `stf local...` from command line without `ldap` and `SSL`, and let me know if your issue persist ?

**Comment by ConfusedMerlin** [comment]
Uh... that server is already in use by some people. I will see to find a way to tests your suggestions, but this might take some time until I manage to set up the system to fit your suggestions. I will report back if done!

**Comment by denis99999** [comment]
If you login using LDAP, only one administrator user is possible, I don't know what is present in your database but normally it doesn't matter, perhaps you have to restart from a new recreated database, also can you provide the full stack error you met ?

**Comment by denis99999** [comment]
It's not possible to delete the default group via API or GUI, so I guess it was deleted some other way, anyway it's not allowed or supported and this naturally makes the system inconsistent and unstable, yes it looks like that is the root of your issue

**Comment by ConfusedMerlin** [comment]
Good Morning,

a little update today. I made my way to the rethinkDB web gui and had a look in there. As it seems the claims of "common group was deleted" are wrong, because I found the Common group inside the groups table. Which is good, I think. Also I am seeing a foreign-key for gorups inside the device-table... if everythink fails, could I reassign the group using a query in there, or would that break even more? (somehow I expect the second one...)
 
Sadly I am still a bit away from having a situation to recreate the checks you requested. I will come back once this was accomplished.

**Comment by denis99999** [comment]
No it is forbidden to manually modify the `rethinkdb` database especially if you don't know exactly what you are doing, especially on the built-in objects like the default group or the admin user, it seems that these objects have been altered what suggests `wrappedlockGroupByOwner()` fails, it's hard for me to help you more remotely... probably the best thing you can do is come back from a clean database by reading the `GroupFeatures.pdf` documentation carefully (including section 10 "Database migration") as well as the `Running` section of the `Readme.md`

**Comment by ConfusedMerlin** [comment]
Greetings,
I will try to purse the "fresh db" way. And I am slowly getting support in the Project Group to get a fresh start with the device farm. Thing is, we do have 50 active devices, sorted into 12 groups with a total of 100 users. Now finding a way to agree all people involved into re-setup is... a bit complicated. 

Beside this,  I still try to fix the existing database. Having a working dump of it now makes things a bit more easy, because I can waste it in a test environment. And i managed to get the inital error go away... at the cost of getting a new one. 

Now adding to groups works find, but when trying to remove, it does not find the phone (instead of being busy). This happens when using the button on the page, as well as when I directly do a curl to the API part (the groups engine, as you call it?) using a token. 
The device in question is fresh, not from the old corrupted db, and it is actually usable.:

<img width="1395" alt="Bildschirmfoto 2022-06-01 um 08 51 37" src="https://user-images.githubusercontent.com/29836528/171345648-8af08ed0-6762-48eb-a37b-24c0e9a0d69b.png">

To get here, I fixed the admin (only one, and its a true admin) and the Common group (only one, and its Delete button is finally greyed out) by deleting them from the rethinkDB and restarting the whole contraption we have, while making sure that the STF_ evironment variables are set correctly and out ldap has the same idea of what the admin should look like the other instances. 

I wonder if I can get the 404 going away too...  
Same effect on all phones, no mater if new or existing in that dump.

**Comment by ConfusedMerlin** [comment]
Sooo... I just found out that in its current state when creating a new group we can add and remove new and old phones without problems again.
But groups from "before" (well, the old ones) still wont let me remove added devices. I first thought it was because their owner was pointing to the invalid user-administrator I got rid of recently. But updating the owner information, so it represents the correct administrator account did not re-enable the ability to remove added phones.  There must be something else that does is different  to new groups I not fond yet. 

Small steps...

**Comment by ConfusedMerlin** [comment]
Oh dear, because inside the groups there is an email of the old double administrator listed, the "404 device not found" message appears. I had to empty the list of users and re-add all of them - except for the invalid old administrator - and suddenly the Group addition and removal does work like a charm again....

I did not expect a non existing mail address inside the group's user array would lead to a "device not found" message. Dear Dev, if you read this: why must that happen?

I can fix out database now... to a degree. Making it fresh is still favourable, but this solution works with "just" re adding existing user accounts to existing groups with existing devices.  It will buy us time until we find a time slot where we can redo the whole thing from zero. 

The final workflow from "server busy" to "works again" now looks like this:

1. double "administrator account", because someone thought the mail-address must be changed detected
2. setting the correct administator account and mail in the stf environment variables
3. setting the correct administrator account inside our ldap db
4. removing both from within the rethinkdb
5. login again, and only one real administrator remains
6. finding two or three (depending if I looked a the original db or a dumped or an imported one) Common groups, none of who is actually listed under settings/groups, but one of them is under groups
7. Also, another group is supposed to be the Default Group but does not act like it
8. Setting the wanted Default group name ("Common" again) in the stf environment variables
9. inside the rethinkdb, remove all "Common" groups, without mercy, and also  the not-working not-Common-named Default Group
10. restart all of stf, only one default group "Common" remains, that acts the way it is supposed to be
11. now the error this ticket changes from "server busy" to "device not found"... great
12. if totally new groups are created, the add/remove does work as intended
13. slowly touching about everything inside the groups database object of an old group to see what is different
14. noticing that the old, wrong, double admin's mailaddress (from point 1) is listed in the group as a user (why mailaddress, btw?)
15. my rethink-db voodoo is not yet powerful enough to just extract this wrong email, so I just empty the whole array inside the rethinkdb (because that user is not visible in the gui group's user view)
16. then I re-add all users from before (including the actual admin!) back to the group inside the gui group view
17. And... tadaa, I can add and remove devices from that group again
18. Still, the users contain links to wrong groups, which might even not exist any more... so I expect to encounter more funny errors at other places.

*sigh* 
And all of this, because someone thought the admin needs another mail and the "Common" group sounds dumb.
