### ISSUE TITLE
Asus Zenpad 10 cannot:  Error: Not found; no service started.

### ISSUE THREAD

**Issue by tavro** [DeviceFarmer/stf#540]
**What is the issue or idea you have?**

I am not able to connect my Asus Zenpad 10 to STF.
```
"Error: Not found; no service started."
stf-dev          |     at /app/lib/units/device/plugins/service.js:104:23
stf-dev          | From previous event:
stf-dev          |     at /app/lib/units/device/plugins/service.js:79:14
stf-dev          |     at runCallback (timers.js:789:20)
stf-dev          |     at tryOnImmediate (timers.js:751:5)
stf-dev          |     at processImmediate [as _immediateCallback] (timers.js:722:5)
```
I think it might be related to the STFService.apk version but I'm not totally sure.

**Comment by ConfusedMerlin** [comment]
We had stuff like that happen to our devices too... 
First thing you could try is Discoonect, uninstall the STFService.apk, restart, reconnect. The devicefarm should then install the STF Service again. 
If that does not work, you might need to crawl into a adb shell leading to it, then finding all packages related to the stf and purging them manually.

If your Phone does have some kind of enterprise protection stuff installed (like... whatwasitsname... Knox!) , it might hinder your progress too.  These can totally disable your ability to install anything over USB. One should be able to set up these Apps so USB Installation is allowed again, but I don't know anything about these beside "it exists" and "it can cause such problems". The people affected by that seem to solve this by doing "re-enrollment", however this works.

You can also try to activate  the "disable timelimit for adb authentication" setting in the dev options of the device. 

If it still does not work... well, Sir, you have a real problem.

**Comment by tavro** [comment]
These adb commands seems to have fixed it.
```
am start -n jp.co.cyberagent.stf/.IdentityActivity
am startservice  -n jp.co.cyberagent.stf/.Service
```

STFService is now running, but the device does not show up in the devices list in the GUI for some reason.
However it does show up when running the command `adb devices -l`

**Comment by tavro** [comment]
Nevermind, that fixed it. The reason it did not show up in the GUI was related to other changes in the code base that I've made myself.
