### ISSUE TITLE
Uploading a general file to device through code

### ISSUE THREAD

**Issue by tavro** [DeviceFarmer/stf#548]
**What is the issue or idea you have?**
This is more of a question.
What is the process of getting a file from your computer onto a physical device through the code base?
Let's say i want to upload a file that is neither an apk or an image, so I make a plugin for that. I upload the file to the plugin.
But how do I get the file from the server onto the device?

I would guess it is similar to how you mount an apk, but I am not really sure about how this processe is actually working and what is happening in the background.

**Comment by denis99999** [comment]
@tavro , I'm not sure to have well understood your question, is your need is to have the possibility to upload a file to the device from the File Explorer UI ?

**Comment by tavro** [comment]
@denis99999 yes, that is my need! 

I understand that this is not yet implemented, but I'm trying to implement it and do not really understand what the flow is supposed to be. 

In the end I guess the key function would be adb.push ?
