### ISSUE TITLE
Deleting-Button disconnected devices from settings does not delete them

### ISSUE THREAD

**Issue by ConfusedMerlin** [DeviceFarmer/stf#561]
yeah... its me again. :D

### **What is the issue or idea you have?**

Well, we do have a couple of old entries inside the productive device farm, which actually predate my first day of work for this particular devicefarm. They were attached once, as some kind of test, or removed from duty, when their batteries started to bloat.  But no one did remove them from the list of devices after that, because...I don't know. 

Now they start to pile up, but we cant get rid of them. When hitting he delete-button in the devices menu, the pop up appears, that asks "are you sure?". Confirmig that, a moment of nothing-happens passes by, followed by the settings menu reappearing. The device we want to delete, however, is still there. 

But not all disconnected devices resist their deletion. Some just go away, as expected. 

In both cases our proxy container (the nginx) logs the HTTP DELETE happening there, and both cases (gets deleted and not gets deleted) returns 200-OK. In fact, there seems to be no difference in between a successful and not successful delete. 

### **Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

It took some testing to figure out the pattern of this bug:

1. devices, which where added recently and then removed were removable
2. devices, which were disconnected for a long time and stayed in there because nobody cared, were not removable
3. attached devices work as expected

Looking for the point in time that separates "recently" from "a long time ago", I remembered that we had to manually fix some messed up admin and group names not so long ago. This being the only notable event of the farm during my time here, it seemed like a plausible separator between deletable and not deletable.

I did a lot of stuff during the manual fix-up, but... booting up the dev-vm I have for that farm I quickly noticed that "non-deletable" extended itself to ALL devices in there. Except for that one Android I do have here in my basement for testing. 

So, how was this one device different to all the others? It was attached to my VM based devicefarm AFTER i did a rethinkDB restore, to geht all data from the productive devicefarm in there. 

So, that one device was deleted from the VM devicefarm, just by clicking the little bin. All others were not deletable. Attaching that one device back on, unplugging it and deleting it again proved to work again, and again, and again.

_So... the pattern for affected devices is:_

Was part of a database put into service by using rethinkdb restore and a former dump, and has not been attached since ever again. 

Interestingly, I found a way to fix this from command line, see end of bug report

### **Please provide the steps to reproduce the issue.**

1. make a dump of your devicefarm using rethinkdb dump (might need to build an image of rethinkdb that actually contains backup and restore functionality first)
2. put that dump in an empty rethinkdb, using rethinkdb restore
3. all of the devices in the device list that have no attached representation now should be unable to be deleted by the UI delete button

### **What is the expected behavior?**

Well... they are getting delted.

### **Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

Sadly, no. Just above noted "HTTP DELETE 200" which is the complete opposite to a warning

### **Please run `stf doctor` and paste the output here.**

see https://github.com/DeviceFarmer/stf/issues/526#issuecomment-1120929312
that link also contains the docker-compose yaml that represents our system setup 

### **Workaround**

As noted before, I already found a way to fix this... if you have access to the command line

One can do that to get rid of the device:

`curl -k -X DELETE -H "Authorization: YOUR_TOKEN" https://localhost/api/v1/devices/Serial?present=false`

That is mostly what the button does do... thanks to an oversight of me, I did not put the url in quotations marks, so it cut off everything with an &, leving only that call as shown above to be executed... and that worked (real url works too, as does localhost)

That is what the nginx logs, first the not working call, second the working call:

`nginx_1                 | 192.168.80.1 - - [08/Aug/2022:10:17:01 +0000] "DELETE /api/v1/devices/HZQN1876BAL42701381?present=false&booked=false&annotated=false&controlled=false HTTP/1.1" 200 51 "https://our-url.de/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:103.0) Gecko/20100101 Firefox/103.0"

nginx_1                 | 192.168.80.1 - - [08/Aug/2022:10:17:25 +0000] "DELETE /api/v1/devices/HZQN1876BAL42701381?present=false HTTP/1.1" 200 49 "-" "curl/7.68.0"`

So it must be one of the & params, but... why does it still say "200", even if nothing was deleted? I am confused... but at least I do have a workaround at hand.

**Comment by ConfusedMerlin** [comment]
@denis99999 
I admit that you are right about my lack of understanding.  

When that http DELETE means "a device with serial y AND is disconnected AND is not booked AND has no comment AND is not used currently", than... well, ALL devices in that farm do have a comment, that tells about which usb hub its plugged in. You are not telling me, that the deletion fails without any feedback, because somebody wrote "hub 4, port 1; battery damaged" in that comment field, aren't you?

Must... test....

Well... after removing the comment, it disappeared out of the farm. Not instantly, but after some refreshing one of these phones is gone. Finally.  Thank you for that hint about the AND conditions.

But I can't do anything to get the "no annotation" comment out of the button without tempering with the angularCode that represents it, can't I?

**Comment by denis99999** [comment]
> well, ALL devices in that farm do have a comment, that tells about which usb hub its plugged in. You are not telling me, that the deletion fails without any feedback, because somebody wrote "hub 4, port 1; battery damaged" in that comment field, aren't you?

As already said, this API fails only in case of server side error or in case the serial number is unknown or in case of bad credentials, and it successes in all other cases, so you understand that success does not mean mandatory deletion of the device. If you want an unconditional deletion of a device, you have to set all filters to the `any` value (i.e. using the `filters` button), you can also remove only some filters of the condition by setting their value to `any`, that is in your case by setting `annotated` to `any` value

> But I can't do anything to get the "no annotation" comment out of the button without tempering with the angularCode that represents it, can't I?

Sorry I didn't well understand your question ?

**Comment by ConfusedMerlin** [comment]
> > But I can't do anything to get the "no annotation" comment out of the button without tempering with the angularCode that represents it, can't I?
> 
> Sorry I didn't well understand your question ?

Pardon my late reply, we hat a situation with a (now former) customer that kept me from responding.
What I was trying to ask was: in order to get the "mandatory deletion" you describes (with the any filters) from that button inside the settings/devices, I would have to modify the actual angularJS code, that creates this button, don't I?
Or did I completely miss a place in the weg gui of the farm where you can change the filter of these generated buttons?

**Comment by denis99999** [comment]
I'm having trouble understanding you, in particular I don't see what you mean with the notion of "generated buttons", it doesn't exist, then there is no need to modify the code, the `filters` button in the `Settings->Devices` menu is precisely designed to set the desired behavior, in your case, if you want an unconditional deletion, you must first position the different `filters` at the value `any`, as in this [example](https://user-images.githubusercontent.com/22766602/185128027-b1d616eb-3e46-42ab-9a09-d7ef694d961c.png), after which just click on the global `Remove` button to get the desired effect, I think I can't be any clearer on this issue

**Comment by ConfusedMerlin** [comment]
> I'm having trouble understanding you, in particular I don't see what you mean with the notion of "generated buttons", it doesn't exist, then there is no need to modify the code, the `filters` button in the `Settings->Devices` menu is precisely designed to set the desired behavior, in your case, if you want an unconditional deletion, you must first position the different `filters` at the value `any`, as in this [example](https://user-images.githubusercontent.com/22766602/185128027-b1d616eb-3e46-42ab-9a09-d7ef694d961c.png), after which just click on the global `Remove` button to get the desired effect, I think I can't be any clearer on this issue

Aaaah... goddammit, that was the hint I needed! :D  Thank you!
That little Button with "Bin-Symbol Filters" up there... I wasn't really aware of it and what it is used for, most likely 
 because I use a rather small screen, and that area disappears as soon as I scroll just a little bit down. 

Anyway. Now with all Filters set to Any, that "Bug" is certainly proven not-buggish. 
And I was at least correct about my inability to spot and use existing features correctly.

**Comment by denis99999** [comment]
> That little Button with "Bin-Symbol Filters" up there... I wasn't really aware of it and what it is used for, most likely

It is described in the `GroupFeature.pdf` documentation.
