### ISSUE TITLE
STF and LDAP configuration

### ISSUE THREAD

**Issue by Polishek** [DeviceFarmer/stf#568]
I've been struggling with proper configuration of the STF to connect to LDAP for one week.
It seems like STF and LDAP are not connected. 
I use docker and start the container with command
`docker run -d --name stf --net host openstf/stf stf local --auth-type ldap --public-ip xxx.xxx.xxx.xxx`

I've set the variables
`
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
STF_AUTH_LDAP_APP_URL="http://xxx.xxx.xxx.xxx:7100"
STF_AUTH_LDAP_LDAP_BIND_CREDENTIALS=
STF_AUTH_LDAP_LDAP_BIND_DN="cn=admin,ou=Teams,ou=People,ou=Services,ou=Groups,o=organizationalUnit"
STF_AUTH_LDAP_LDAP_SEARCH_CLASS=
STF_AUTH_LDAP_LDAP_SEARCH_DN="ou=People,o=organizationalUnit"
STF_AUTH_LDAP_LDAP_SEARCH_FIELD="uid"
STF_AUTH_LDAP_LDAP_SEARCH_SCOPE=
STF_AUTH_LDAP_LDAP_TIMEOUT=
STF_AUTH_LDAP_LDAP_URL="ldap://localhost:389"
STF_AUTH_LDAP_LDAP_USERNAME_FIELD="uid"
STF_AUTH_LDAP_PORT=` but I'm not sure if I understand them correctly.
I created few accounts in LDAP Account Manager but when I try to login to stf (_auth/ldap/_) I get error:

> `Server error. Check log output.`

I am out of ideas what I can do more to make this work.

**Comment by denis99999** [comment]
@Polishek , you have first to check the log, and to help you here is an example that should works:
```
docker run -d --name stf --net host devicefarmer/stf \
  stf local \
    --auth-type ldap \
    --auth-options '["--ldap-url","ldap://localhost","--ldap-search-dn","dc=XXX,dc=YYY","--ldap-bind-dn","cn=admin,dc=XXX,dc=YYY","--ldap-bind-credentials","YOUR_ADMIN_PASSWORD","--ldap-search-field","uid"]' \
    --public-ip YOUR_IP
```

**Comment by Polishek** [comment]
That works perfectly, thakns!
