### ISSUE TITLE
Android 11 Support

### ISSUE THREAD

**Issue by 0898holly** [DeviceFarmer/stf#58]
Android 11 is not supported for me. Is this something I'm doing wrong or is there somthing in the pipeline for this please?

**Comment by Babu-SKK** [comment]
Android 11 support is depends on the minicap lib. You can find the more details here https://github.com/DeviceFarmer/minicap/issues/3

**Comment by pcrepieux** [comment]
We are making progress on this topic. 
As minicap requires to be compiled against AOSP source code, we need it to be fully synced with the android releases but that is not always the case. 
To overcome this constraint, we are working on an alternative implementation.

**Comment by nicodeur** [comment]
Hello,

Seems to be resolve on minicap by https://github.com/DeviceFarmer/minicap/pull/7

It is release on [2.5.0](https://github.com/DeviceFarmer/minicap/releases/tag/v2.5.0) of minicap.

Possible to release a new version of stf with this change ?

**Comment by koral--** [comment]
Just merged: https://github.com/DeviceFarmer/stf/pull/109

**Comment by nicodeur** [comment]
Hello,

I confirm I have an Android 11 which works now !

![image](https://user-images.githubusercontent.com/6707556/95308679-7ff1e380-088a-11eb-9a3c-5db50034ff6e.png)

Thanks a lot.
