### ISSUE TITLE
swagger error : Errors Hide Parser error on line 28 end of the stream or a document separator is expected

### ISSUE THREAD

**Issue by namilkimfree** [DeviceFarmer/stf#600]
**What is the issue or idea you have?**

 docker run -p 8080:8080 -v /data/stf/swagger/:/foo -e "VALIDATOR_URL=null"  -e "SWAGGER_JSON=/foo/api_v1.yaml" -d  swaggerapi/swagger-ui:latest

http:x.x.x.x:8080/

swaager error show:

Errors Hide Parser error on line 28 end of the stream or a document separator is expected

swagger api_v1.yaml using to  https://github.com/DeviceFarmer/stf/blob/master/lib/units/api/swagger/api_v1.yaml

file location: /data/stf/swagger/api_v1.yaml

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

**Please provide the steps to reproduce the issue.**

1. mkdir -p /data/stf/swagger/
2. download api_v1.yaml file to /data/stf/swagger/api_v1.yaml
3. docker run -p 8080:8080 -v /data/stf/swagger/:/foo -e "VALIDATOR_URL=null"  -e "SWAGGER_JSON=/foo/api_v1.yaml" -d  swaggerapi/swagger-ui:latest

4. visit x.x.x.x:8080

**What is the expected behavior?**

non error swaager

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

**Please run `stf doctor` and paste the output here.**

**Comment by denis99999** [comment]
@namilkimfree , try to change the `latest `tag to `3.22.3` and let me know if it works or not ?

**Comment by namilkimfree** [comment]
@denis99999  thank you, just success :)
