### ISSUE TITLE
help me,an error while installing the dependency

### ISSUE THREAD

**Issue by csdaa** [DeviceFarmer/stf#609]
Good evening sir:
    I just downloaded the source code for the latest version of stf, then I executed npm install. and then the error alerts kept coming without stopping. I tried to use the npm install command to install the packages in the webpack file one by one, and finally solved the problem by installing most of them, but there are still some packages that can't be downloaded.
   I think I'm not the only one having this problem, I'd like to write an installation manual, can you guys give me some technical support? I've written the installation manual and will make it available for everyone to read for free to help people who need stf.
  Thanks

**Comment by csdaa** [comment]
This is the error message I encountered:
===================================================================
E:\proj\stf-master>npm install swagger-express-mw-node12@^0.7.0
npm WARN deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN checkPermissions Missing write access to E:\proj\stf-master\node_modules\swagger-node-runner\node_modules\body-parser
npm WARN checkPermissions Missing write access to E:\proj\stf-master\node_modules\swagger-node-runner
npm WARN checkPermissions Missing write access to E:\proj\stf-master\node_modules\swagger-node-runner\node_modules
npm ERR! path E:\proj\stf-master\node_modules\swagger-node-runner\node_modules\body-parser
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall access
npm ERR! enoent ENOENT: no such file or directory, access 'E:\proj\stf-master\node_modules\swagger-node-runner\node_modules\body-parser'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\nodejs\node_cache\_logs\2022-11-01T10_59_48_054Z-debug.log
===================================================================

**Comment by denis99999** [comment]
@csdaa please fill the issue template, and tell me what is your node version ?

**Comment by csdaa** [comment]
> @csdaa please fill the issue template, and tell me what is your node version ?

v11.5.0

====================================================================


**What is the issue or idea you have?**
issue

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

no

**Please provide the steps to reproduce the issue.**

npm install 

**What is the expected behavior?**

correct installation dependencies

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

Not there yet

**Please run `stf doctor` and paste the output here.**
Not there yet

**Comment by denis99999** [comment]
@csdaa , please upgrade node to 17.9.0 version

**Comment by csdaa** [comment]
> @csdaa , please upgrade node to 17.9.0 version

thank youu very much!

**Comment by csdaa** [comment]
> @csdaa , please upgrade node to 17.9.0 version

```
fatal: unable to access 'https://github.com/swimlane/ng-context-menu.git/': OpenSSL SSL_read: Connection was reset, errno 10054

```
I have encountered several inaccessible prompts
can you give me a little help

**Comment by denis99999** [comment]
@csdaa ,

Sorry, but as specified in `README.md` on `Windows` we don't provide any installation support, why don't you use STF using `Docker` it will be more simple ?

That being said, by taking a look on `Google` I saw this solution for your problem hoping it will solve it:
```
 git config --global http.sslVerify "false" 
 git config --global https.sslVerify "false"
```
And if you pass, do a Pull Request to complete our installation procedures!
