### ISSUE TITLE
Devices are not displayed in the docker container when working on a virtual machine

### ISSUE THREAD

**Issue by gamalulik** [DeviceFarmer/stf#614]
I deployed device farmer in different ways, but now I have this configuration: the main station on Windows Server 2019, to which mobile phones are connected and virtual machines are deployed. A docker container with the project is deployed on a Linux 22.04 virtual machine. The project was launched using these commands: 

Start Docker
-         1. Start Docker and check dashboard
Pull Docker Images
- 	1. sudo docker pull rethinkdb
-         2. sudo docker pull devicefarmer/stf:latest
Create Folder For Rethinkdb
- 	 mkdir /home/<my user>/RethinkDB
- 	 export RETHINK_DB=/home/<my user>/RethinkDB

Start Containers
-        docker network create df-network
-        docker run -d --network=df-network --name rethinkdb -p 28015:28015 -v $RETHINK_DB:/data rethinkdb rethinkdb --bind all --cache-size 8192 --http-port 8090
-        adb start-server
-        docker run --network=df-network -e STF_ADMIN_NAME=myadmin -e STF_ADMIN_EMAIL=myadmin@myadmin.com -e RETHINKDB_PORT_28015_TCP=tcp://rethinkdb:28015 -p 7100:7100 -p 7110:7110 -p 7400:7400 -p 7408:7408 -p 7404:7404 -it devicefarmer/stf:latest stf local --adb-host adb --public-ip <my-ip>

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

When executing the command adb devices -l, all devices are displayed on the virtual machine, but they are not visible in the web version of STF 

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
[logs stf local.txt](https://github.com/DeviceFarmer/stf/files/9960746/logs.stf.local.txt)

**Please run `stf doctor` and paste the output here.**
[logs stf doctor.txt](https://github.com/DeviceFarmer/stf/files/9960780/logs.stf.doctor.txt)

Container Logs: 
[logs stf container.txt](https://github.com/DeviceFarmer/stf/files/9960782/logs.stf.container.txt)

**Comment by denis99999** [comment]
@gamalulik ,
You have log errors, so anyway it can't work properly !

In general way, I recommend you to deploy `STF` in full deployment mode (cf. `DEPLOYMENT.md` for help) instead in development mode said also local mode which is reserved only for development purposes and is not supported in production mode.

I think your main problem is that you provide your loopback address as the public IP instead to provide an external IP accessible from outside, for instance the IP attached to your external interface. Moreover, you have also to launch your `rethinkdb` and `STF` docker images using the `--net host` option, so supposing `ADB` is available in your linux machine and you have configured your virtual machine network interface using `bridge adapter` mode, you have to launch `STF` and `rethinkdb` as follow (minimal template) in order `STF` well detect your mobile phones attached to your virtual machine:
```
# docker run -v $RETHINK_DB:/data --net host devicefarmer/rethinkdb:latest rethinkdb ...
# docker run --net host devicefarmer/stf:latest stf local --public-ip YOUR_EXTERNAL_IP_ADDRESS ...
```
That should work !
