### ISSUE TITLE
Can't control phone after appium is running

### ISSUE THREAD

**Issue by csdaa** [DeviceFarmer/stf#631]
**What is the issue or idea you have?**
Can't control phone after appium is running

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
ZY2246Z52M             device product:kuntao model:Lenovo_P2c72 device:kuntao transport_id:30

**Please provide the steps to reproduce the issue.**
1. Run appium
2. After appium ends, control the phone

**What is the expected behavior?**
After appium ends, the phone can be controlled

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
INF/util:procutil 36953 [*] Forking "/app/lib/cli storage-temp --port 7102"
INF/util:procutil 36953 [*] Forking "/app/lib/cli storage-plugin-image --port 7103 --storage-url http://localhost:7100/"
INF/util:procutil 36953 [*] Forking "/app/lib/cli storage-plugin-apk --port 7104 --storage-url http://localhost:7100/"
INF/util:procutil 36953 [*] Forking "/app/lib/cli poorxy --port 7100 --app-url http://localhost:7105/ --auth-url http://localhost:7120/ --api-url http://localhost:7106/ --websocket-url http://localhost:7110/ --storage-url http://localhost:7102/ --storage-plugin-image-url http://localhost:7103/ --storage-plugin-apk-url http://localhost:7104/"
lib/cli triproxy [name]

Options:
  -h, --help         Show help.                                        [boolean]
  -V, --version      Show version.                                     [boolean]
  --bind-dealer, -d  The address to bind the ZeroMQ DEALER endpoint to.
                                              [string] [default: "tcp://*:7112"]
  --bind-pub, -u     The address to bind the ZeroMQ PUB endpoint to.
                                              [string] [default: "tcp://*:7111"]
  --bind-pull, -p    The address to bind the ZeroMQ PULL endpoint to.
                                              [string] [default: "tcp://*:7113"]
  --name             An easily identifiable name for log output.
                                              [string] [default: "030a608731a7"]

Each option can be be overwritten with an environment variable by converting the
option to uppercase, replacing dashes with underscores and prefixing it with
`STF_TRIPROXY_` (e.g. `STF_TRIPROXY_BIND_PUB`).

Address already in use
FTL/cli:local 36953 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/app/lib/util/procutil.js:49:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
INF/cli:local 36953 [*] Shutting down all child processes
INF/util:lifecycle 36979 [*] Winding down for graceful exit
INF/db 36979 [*] Connecting to rethinkdb:28015

**Please run `stf doctor` and paste the output here.**
INF/cli:doctor 37129 [*] OS Arch: x64
INF/cli:doctor 37129 [*] OS Platform: linux
INF/cli:doctor 37129 [*] OS Platform: 4.18.0-348.7.1.el8_5.x86_64
INF/cli:doctor 37129 [*] Using Node 8.9.3
INF/cli:doctor 37129 [*] Using ZeroMQ 4.1.4
ERR/cli:doctor 37129 [*] RethinkDB is not installed (`rethinkdb` is missing)
ERR/cli:doctor 37129 [*] ProtoBuf is not installed (`protoc` is missing)
ERR/cli:doctor 37129 [*] ADB is not installed (`adb` is missing)
INF/cli:doctor 37129 [*] Using GraphicsMagick 1.3.23

**Comment by denis99999** [comment]
@csdaa ,
The "`Address already in use`" log error indicates that `Appium` is using the same address/port already in use by `STF`!

Note that you should not run `Appium` on the same machine as `STF`, in fact it is forbidden for a client like `Appium` to take control of devices locally using the `ADB` command because it causes a service interaction (conflict of access => inconsistency => instability) between `STF` and the client via the local use of `ADB`.

The correct way for a client to do this is to use the `STF API` and the "`ADB connect...`" command to take control of a device, so this should be over the network and only over the network, the rest is forbidden, dirty and not covered by support, if you have a performance problem, all you have to do is co-locate the `STF` machine and the client machine on the same local network.

**Comment by csdaa** [comment]
Thank you very much for your help
It is really unreasonable to do so at present, I think of other ways
