### ISSUE TITLE
Upgraded v3.6.5, stfserver pop-up red box

### ISSUE THREAD

**Issue by threescholars** [DeviceFarmer/stf#665]
![image](https://github.com/DeviceFarmer/stf/assets/20198437/4a7f627c-db63-45d9-915e-32c1121d5f96)

Upgraded v3.6.5, the phone has been popping up this stfserver problem, what is this problem

**Comment by denis99999** [comment]
@threescholars look at [OpenSTF 3.4.0 enhancements](https://github.com/openstf/stf/blob/master/CHANGELOG.md#340-2018-08-09)
