### ISSUE TITLE
an error occurred during the installation process using npm

### ISSUE THREAD

**Issue by AaronAn58** [DeviceFarmer/stf#668]
sudo npm install -g @devicefarmer/stf

npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/fintechx/swagger-node-runner.git
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

**Comment by denis99999** [comment]
@AaronAn58 try to protect '@' character like this : `sudo npm install -g \@devicefarmer/stf`, let me know if it fixes your issue!

**Comment by AaronAn58** [comment]
Hi denis,
   thank you for you reply.
same problem when I run sudo npm install -g \@devicefarmer/stf like this:
sudo npm install -g \@devicefarmer/stf
npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/fintechx/swagger-node-runner.git
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: 无法读取远程仓库。
npm ERR! 
npm ERR! 请确认您有正确的访问权限并且仓库存在。

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-06-09T09_24_27_794Z-debug-0.log

**Comment by AaronAn58** [comment]
Hi denis,
I have successfully installed this software as root user. Thank you
