### ISSUE TITLE
FAILED: CMakeFiles/jpegturbo.dir/src/exports.cc.o

### ISSUE THREAD

**Issue by konsumer** [DeviceFarmer/stf#671]
**What is the issue or idea you have?**

Won't build

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

No, I can't build, with `npm install` at all.

**Please provide the steps to reproduce the issue.**

**What is the expected behavior?**

It should build & install dependencies. It looks like it's failing on C++ build of jpeg-turbo.

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

Here is log from `npm install`:
[error.log.zip](https://github.com/DeviceFarmer/stf/files/11709330/error.log.zip)

**Please run `stf doctor` and paste the output here.**

Cannot install, so this will not work.

Mac M1 Ventura
Node: 20.0.0
Npm: 9.6.4

From `master`

**Comment by denis99999** [comment]
@konsumer I will take a look on your issue on monday, but waiting for that as a workaround you should try to build using the 17.9.0 version of Nodejs, let me know if it fixes your problem!
