### ISSUE TITLE
[Query] Can I create 2 different STF servers and connect them to another centralised server?

### ISSUE THREAD

**Issue by sunilkn006** [DeviceFarmer/stf#690]
**What is the issue or idea you have?**

I have a query on one of a scenario. 
* Lets say I create 2 STF servers - say Server1 consisting of 3 devices and Server2 consisting of 5 devices. 
* Both of these servers are at 2 different locations - say different geographies.

Query - 
* Is it possible for us to connect these 2 STF servers to a common server and access 3+5 = 8 devices without me needing to use 2 different server URLs?
* If I use the URL of common server, I should be able to access all the 8 devices.

**Comment by denis99999** [comment]
@sunilkn006 yes of course STF is made for that, see [`DEPLOYMENT.md`](https://github.com/DeviceFarmer/stf/blob/master/doc/DEPLOYMENT.md) documentation for details about such distributed architecture!

**Comment by sunilkn006** [comment]
Thanks @denis99999 
Let me check the documentation

**Comment by sunilkn006** [comment]
Hi @denis99999 
Any information around this please?

**Comment by denis99999** [comment]
@sunilkn006  I already answered you about that, I add that `stf local` is not supported in production mode but it is reserved for development purpose, so if you want a distributed architecture you have to conform to the `DEPLOYMENT.md` model, I add also that Mac OS is not recommended but you have to prefer Linux OS wich is fully supported.

**Comment by sunilkn006** [comment]
Thanks @denis99999 
Let me figure it out.
