### ISSUE TITLE
The software is uninstalled after the connection is disconnected.

### ISSUE THREAD

**Issue by qianmianyao** [DeviceFarmer/stf#706]
**What is the issue or idea you have?**
When installing software on the web, there is a chance that the device will disconnect and all installed software inside will be uninstalled.

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
This situation will appear on all devices.

**Comment by koral--** [comment]
This is the default behavior.
You can start the provider with `--no-cleanup` option to change that.
