### ISSUE TITLE
After controlling 15 mobile phones, STF became very stuck.

### ISSUE THREAD

**Issue by csdaa** [DeviceFarmer/stf#729]
**What is the issue or idea you have?**
After mounting 15 mobile phones, stf access is very slow。
I use two computers to connect these mobile phones. The computer configuration is the latest version of Win10, Intel Core 10th generation I7 CPU, 32G memory, and industrial-grade USB-hub. The STF program runs separately on another computer, and the three computers are connected by a Gigabit enterprise network.

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
It has nothing to do with the equipment

**Please provide the steps to reproduce the issue.**
Connect 15 devices and let 15 people operate them at the same time. I find that the screen freezes, like a ppt.

**What is the expected behavior?**
How many devices can the current version of STF control at the same time?
The version I am currently using is 3.6.1. How can I modify it so that it can be used by more people at the same time? Could you please give me some advice? Thank you.
 
**Please run `stf doctor` and paste the output here.**
2023-11-15T11:36:57.589Z INF/cli:doctor 139993 [*] OS Arch: x64
2023-11-15T11:36:57.596Z INF/cli:doctor 139993 [*] OS Platform: linux
2023-11-15T11:36:57.597Z INF/cli:doctor 139993 [*] OS Platform: 4.18.0-348.7.1.el8_5.x86_64
2023-11-15T11:36:57.597Z INF/cli:doctor 139993 [*] Using Node 8.9.3
2023-11-15T11:36:57.642Z INF/cli:doctor 139993 [*] Using ZeroMQ 4.1.4
2023-11-15T11:36:57.704Z ERR/cli:doctor 139993 [*] RethinkDB is not installed (`rethinkdb` is missing)
2023-11-15T11:36:57.704Z ERR/cli:doctor 139993 [*] ProtoBuf is not installed (`protoc` is missing)
2023-11-15T11:36:57.705Z ERR/cli:doctor 139993 [*] ADB is not installed (`adb` is missing)
2023-11-15T11:36:57.707Z INF/cli:doctor 139993 [*] Using GraphicsMagick 1.3.23

**Comment by denis99999** [comment]
@csdaa , please provide the STF configuration (command line, docker-compose file, etc.) on each computer, how devices are connected to the computer ?

**Comment by csdaa** [comment]
Hello Mr. @denis99999 
Can I ask you a few questions:
How many devices can stf control at the same time?
Which deployment method can maximize its performance?

**Comment by csdaa** [comment]
Hello Mr. @denis99999 
We only have one server, so I can only give you a piece of STF configuration information.
We use the connection mode of mobile phone to hub and hub to computer host.
for example:
We use 7 mobile phones to connect to the first hub, and then the first hub is connected to the first host. The host is connected to the server through the switch.

The server and the node are connected through the adb exposed port. The node exposes the port through the command: "adb nodaemon server -a -P 5037", and the server executes "stf provider --name TestNode --min-port..."


**docker-compose:**
`version: "3"

services:
  rethinkdb:
    container_name: rethinkdb
    image: rethinkdb:2.3
    restart: unless-stopped
    volumes:
        - "rethinkdb-data:/data"
    command: "rethinkdb --bind all --cache-size 2048"

  adb:
    container_name: adb
    image: devicefarmer/adb:latest
    restart: unless-stopped
    volumes: 
      - "/dev/bus/usb:/dev/bus/usb"
    privileged: true

  stf:
    container_name: stf
    image: devicefarmer/stf
    ports:
      - "7100:7100"
      - "7110:7110"
      - "7400-7500:7400-7500"
    environment:
      - TZ='America/Los_Angeles'
      - RETHINKDB_PORT_28015_TCP=tcp://rethinkdb:28015
      - STF_ADMIN_EMAIL=aa@qq.com
      - STF_ADMIN_NAME=aa@qq.com
    restart: unless-stopped
    command: stf local --adb-host adb --public-ip 192.168.8.132 --provider-min-port 7400 --provider-max-port 7500

volumes:
  rethinkdb-data: {}
`
**Connection script for node 1:**
stf provider --name 48.127  --min-port 7400 --max-port 7700 --connect-sub tcp://127.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --group-timeout 900 --public-ip  192.168.63.121 --storage-url http://localhost:7100/ --adb-host 192.168.48.127 --adb-port 5037 --vnc-initial-size 600*800 --mute-master never --allow-remote

**Connection script for node 2:**
stf provider --name 48.81  --min-port 7400 --max-port 7700 --connect-sub tcp://127.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --group-timeout 900 --public-ip  192.168.63.121 --storage-url http://localhost:7100/ --adb-host 192.168.48.81 --adb-port 5037 --vnc-initial-size 600*800 --mute-master never --allow-remote

**Comment by denis99999** [comment]
@csdaa , you have to review your configuration entirely following full deployment example in [DEPLOYMENT.md](https://github.com/DeviceFarmer/stf/blob/master/doc/DEPLOYMENT.md) documentation, in particular you can't use the `stf local` mode in such distributed architecture, `ADB` and `provider` units have to run on the same host where the devices are connected to, `provider` unit have to point to the `triproxy-dev` unit (not to loopback address), etc.


> How many devices can stf control at the same time?

No know limits, it depends of your STF configurations and your material capacities

> Which deployment method can maximize its performance?

cf. [DEPLOYMENT.md](https://github.com/DeviceFarmer/stf/blob/master/doc/DEPLOYMENT.md) documentation

**Comment by csdaa** [comment]
> @csdaa , you have to review your configuration entirely following full deployment example in [DEPLOYMENT.md](https://github.com/DeviceFarmer/stf/blob/master/doc/DEPLOYMENT.md) documentation, in particular you can't use the `stf local` mode in such distributed architecture, `ADB` and `provider` units have to run on the same host where the devices are connected to, `provider` unit have to point to the `triproxy-dev` unit (not to loopback address), etc.
> 
> > How many devices can stf control at the same time?
> 
> No know limits, it depends of your STF configurations and your material capacities
> 
> > Which deployment method can maximize its performance?
> 
> cf. [DEPLOYMENT.md](https://github.com/DeviceFarmer/stf/blob/master/doc/DEPLOYMENT.md) documentation

Thank you for your help
