### ISSUE TITLE
Inquire how to use Android beta 14 in Mac OS environment

### ISSUE THREAD

**Issue by nalawa-yoon** [DeviceFarmer/stf#732]
I was told to install STFservice.apk for version 14 of Android in another issue (#692) and please let me know how to proceed in the Mac OS environment or give me the location of the guide document.

**Comment by denis99999** [comment]
@nalawa-yoon , firstly note Mac OS is not recommended in production mode, instead you have to prefer Linux OS, secondly you have just to follow `readme.md` and `deployment.md` documentation, typically you have just to install the latest docker image of devicefarme/stf as well as ADB and RETHINKDB in order to get an operational solution.

**Comment by nalawa-yoon** [comment]
Thank you, @denis99999 
Like your comment, I tried to install it in Ubuntu, but the current environment is that I have to install it in Ubuntu through a virtual machine in Mac, but there are many restrictions (network allowed ports in the company) due to the network environment, so please guide me if there is any other way I can do it in Mac environment.

And the stf version is Linux, which is 3.6.6 version, and if you download it from Mac, 3.6.4 will be downloaded. Maybe it's because the latest version doesn't work in Mac environment..  If you know anything, please comment.

**Comment by denis99999** [comment]
@nalawa-yoon, STF works well either in a Mac host or in a virtual machine running on a Mac host (e.g. using VirtualBox), and the latest version is indeed 3.6.6, no specific version for Mac, you must therefore carefully check your configuration, finally your company's security policy is not linked to STF.

**Comment by denis99999** [comment]
@nalawa-yoon , sorry I precise for Android 14 compatibility you have to download the docker image of STF with the `latest` tag, that is: `devicefarmer/stf:latest`

**Comment by nalawa-yoon** [comment]
thank you, @denis99999 
We checked the operation of Android version 14 through the installation of the latest version in the Mac environment.
I solved it last week, but I forgot to thank you
Thank you so much for your help.
