### ISSUE TITLE
[Question] how to login admin account in can LDAP authentication 

### ISSUE THREAD

**Issue by kotini** [DeviceFarmer/stf#74]
Hi I configure stf server with ldap authentication .
How can i login to admin account to play with group feature .

**Comment by JoeJoeYuan** [comment]
@kotini 
When you install stf, you can set admin account to your ldap account, I just do like this.
when install whith docker, set admin account with ENV parameters: 
STF_ADMIN_NAME=xxx
STF_ADMIN_EMAIL=xxx@xxx.com
after integate with ldap, this acount is the admin!

**Comment by kotini** [comment]
@JoeJoeYuan  thanks fir update .
I understand 
any ldap name and email id i need to set before starting rethink db .
That name will be admin.

Its working now . thanks .
