### ISSUE TITLE
 How to maintain a long-term connection with the phone, now 15 minutes of not operating the phone will automatically interrupt the connection with the phone

### ISSUE THREAD

**Issue by lin54241930** [DeviceFarmer/stf#77]
There is a problem. If I don't operate the mobile phone for 15 minutes after connecting to the mobile phone, it will automatically disconnect from the mobile phone. However, we need to do not operate the mobile phone for a long time to test the application, rather than let the mobile phone automatically disconnect. There is no relevant code in the source code to automatically disconnect the mobile phone. If possible, can the author tell us how to avoid operating the mobile phone for a long time and not automatically disconnect. 
Every time the phone is connected to the phone for 15 minutes without operation, it will automatically disconnect

Thank you

**Comment by denis99999** [comment]
@lin54241930 , you have tu use the `--group-timeout` parameter at STF launching time, the default value corresponds to 15 minutes.

**Comment by lin54241930** [comment]
> @lin54241930 , you have tu use the `--group-timeout` parameter at STF launching time (i.e. provider unit), the default value corresponds to 15 minutes.


But my startup command is `stf local` and no other startup parameters are used. Have you encountered a similar problem

**Comment by lin54241930** [comment]
> @lin54241930 , you have tu use the `--group-timeout` parameter at STF launching time (i.e. provider unit), the default value corresponds to 15 minutes.


I tried to add this parameter again`--group-timeout` it can not automatically disconnect for more than 15 minutes, thank you very much for your answer
