### ISSUE TITLE
I can't find a way to change 'STF_ADMIN_EMAIL'

### ISSUE THREAD

**Issue by QA-Jihyun** [DeviceFarmer/stf#771]
I'm running STF with a terminal in a MAC environment.

sudo stf local public-ip 111.222.333.444 --allow-remote --auth-type ldap --auth-options '["--ldap-url","ldap://localhost","--ldap-bind- dn","cn=admin,dc=test,dc=com","--ldap-bind-credentials","password","--ldap-search-dn","dc=test,dc=com" ,"--ldap-search-field","uid"]'

I'm running STF with terminal(LDAP), but I can't find a way to change 'STF_ADMIN_EMAIL'.

It appears that it can be changed in STF's Linux environment or in Docker.

I want to know how to change it on MAC.

**Comment by denis99999** [comment]
@QA-Jihyun , take a look at [Running Section of README.md](https://github.com/DeviceFarmer/stf#running), but currently for that your rethinkdb database has to be recreated (e.g. simply delete it first) otherwise the new value of `STF_ADMIN_EMAIL` is not taken into account

**Comment by QA-Jihyun** [comment]
> @QA-Jihyun , take a look at [Running Section of README.md](https://github.com/DeviceFarmer/stf#running), but currently for that your rethinkdb database has to be recreated (e.g. simply delete it first) otherwise the new value of `STF_ADMIN_EMAIL` is not taken into account

I found out that I needed to change the stf admin mail data value in stf's environment file. With your help and searching about rethinkdb, I found out that I needed to change rethinkdb data table to reql, and it worked. Thank you again this time.

**Comment by denis99999** [comment]
@QA-Jihyun ,

> I found out that I needed to change rethinkdb data table to reql

What is it mean ? I hope you did not try to patch STF tables ? Because it would introduce inconsistencies

**Comment by QA-Jihyun** [comment]
> @QA-Jihyun ,
> 
> > I found out that I needed to change rethinkdb data table to reql
> 
> What is it mean ? I hope you did not try to patch STF tables ? Because it would introduce inconsistencies

After running rethinkdb, you can access the address where rethinkdb was run in the browser. 

Afterwards, I used ReQL to query stf's owner.email, and I used ReQL to modify owner.email. (=administrator@fakedomain.com > test@test.com)

If you click 'contact support' in the stf browser after editing owner.email, the onwer.email(test@test.com) address you modified will be designated as the recipient in the mail window. 
<img width="817" alt="스크린샷 2024-04-17 오전 9 06 08" src="https://github.com/DeviceFarmer/stf/assets/109647669/74219b95-398b-4ea7-89c7-9524c7fb60a4">
<img width="1202" alt="스크린샷 2024-04-17 오전 9 07 49" src="https://github.com/DeviceFarmer/stf/assets/109647669/88614bdd-6cfb-4c70-a96a-8037590dfc0c">
<img width="766" alt="스크린샷 2024-04-17 오전 9 06 54" src="https://github.com/DeviceFarmer/stf/assets/109647669/231f2097-7f7c-4d30-88b4-7ef931cd748f">

**Comment by denis99999** [comment]
@QA-Jihyun , very bad thing, as I said you have introduced inconsistencies in the database because admin credentials are anywhere in database, currently I am working on a PR enabling the updating of admin credentials in a safe way.
As I said, currently if you want to change admin credentials, the only clean way is first to delete the database, and then recreate it by launching `stf migrate` or `stf local`
