### ISSUE TITLE
Android 15 and Android 14 with latest patch issue

### ISSUE THREAD

**Issue by sn00wden** [DeviceFarmer/stf#773]
STFservice.apk is not installed at android latest patch and at android 15...

Devices with such rom is in preparing state at STF...

**Comment by jupe** [comment]
Could you provide stf service & phone logcat logs? Might be related to STFService apk permissions.

**Comment by KishanDasani** [comment]
I was able to get pixel devices running on android 14 online on stf after updating the APK with [fix](https://github.com/yaspoon/STFService.apk/commit/8bd7e771194930f8597e7a2147987569898395ed)

Now I am running on a different issue. Screen is not being fetched for pixel devices. 

Examined adb logcat logs and getting error with SurfaceControl as below:

`'SurfaceControl error
    'java.lang.NoSuchMethodException: android.view.SurfaceControl.createDisplay [class java.lang.String, boolean]
    '\tat java.lang.Class.getMethod(Class.java:2950)
    '\tat java.lang.Class.getMethod(Class.java:2450)
    '\tat io.devicefarmer.minicap.utils.SurfaceControl.createDisplay(SurfaceControl.kt:93)
    '\tat io.devicefarmer.minicap.provider.SurfaceProvider.initSurface(SurfaceProvider.kt:87)
    '\tat io.devicefarmer.minicap.provider.SurfaceProvider.initSurface(SurfaceProvider.kt:106)
    '\tat io.devicefarmer.minicap.provider.SurfaceProvider.onConnection(SurfaceProvider.kt:75)
    '\tat io.devicefarmer.minicap.SimpleServer.start(SimpleServer.kt:41)
    '\tat io.devicefarmer.minicap.Main$Companion.main(Main.kt:87)
    '\tat io.devicefarmer.minicap.Main.main(Unknown Source:2)
    '\tat com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
    '\tat com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)'`

Also, stf logs are as below:

```
 [<serial_number>] [19] Installed apps found.
 [<serial_number>] Device SDK : 34
 [<serial_number>] Setting frame producer projection to 767x1134
 [<serial_number>] Keeping 767x1134 as current frame producer projection
 [<serial_number>] Requesting frame producer to start
 [<serial_number>] Not changing quality settings as size is [6.396046316030102]
 [<serial_number>] Launching screen service minicap-bin
 [<serial_number>] Screen jpeg quality  60
 [<serial_number>] Screen fps  8
 [<serial_number>] Missing resources/unknown minicap grabber: minicap-bin
 [<serial_number>] undefined
 [<serial_number>] [10] Running Apps.
 [<serial_number>] minicap says: "/system/bin/sh: undefined: inaccessible or not found"
 [<serial_number>] entered end listener riskystream
 [<serial_number>] entered expected end false
 [<serial_number>] Shell keeping minicap running ended unexpectedly
 [<serial_number>] Capturing screenshot
 [<serial_number>] CLASSPATH=/data/local/tmp/minicap.apk app_process /system/bin io.devicefarmer.minicap.Main -P 1080x2400@1080x2400/0 -s >/data/local/tmp/minicap_1714645570976.jpg
 [<serial_number>] <serial_number> created sucessfully
 [<serial_number>] Disconnecting from minicap service
 [<serial_number>] Stopping minicap service
 [<serial_number>] Not changing quality settings as size is [6.396046316030102]
 [<serial_number>] Launching screen service minicap-apk
 [<serial_number>] Screen jpeg quality  60
 [<serial_number>] Screen fps  8
 [<serial_number>] CLASSPATH=/data/local/tmp/minicap.apk app_process /system/bin io.devicefarmer.minicap.Main -S -Q 60 -P 1080x2400@767x1134/0
 [<serial_number>] minicap says: "04:26:13.367 [main] INFO  BaseProvider - framePeriodMs: 0"
 [<serial_number>] minicap says: "PID: 13379"
 [<serial_number>] minicap says: "INFO: 1080x2400@510x1134/0"
 [<serial_number>] minicap says: "04:26:13.375 [main] INFO  Main - Listening on socket : minicap"
 [<serial_number>] Connecting to minicap service
 [<serial_number>] Reading minicap banner
 [<serial_number>] minicap error: "04:26:13.486 [main] ERROR SurfaceControl - SurfaceControl error"
 [<serial_number>] Shutting down due to fatal error gracefully```

Does anyone has any idea of what is this and how to fix this?

**Comment by sn00wden** [comment]
> Could you provide stf service & phone logcat logs? Might be related to STFService apk permissions.
can you tell me how to do that, please?

also latest 14 android issue was solved by latest [STFService.apk](https://github.com/DeviceFarmer/STFService.apk)

**Comment by sn00wden** [comment]
latest 14 android issue was solved by latest [STFService.apk](https://github.com/DeviceFarmer/STFService.apk)

**Comment by sn00wden** [comment]
Is there any update about support of Android 15 ?

**Comment by sn00wden** [comment]
Issue with android 15 was solved by [STFService.apk v.2.5.3](https://github.com/DeviceFarmer/STFService.apk)
