### ISSUE TITLE
All app minimize on stop controlling

### ISSUE THREAD

**Issue by your-it** [DeviceFarmer/stf#774]
**What is the issue or idea you have?**
After controlling a device, when I stop all app minimize on that device. I want the last app to remain open.

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
No all.

**Please provide the steps to reproduce the issue.**
Use device, stop device

**What is the expected behavior?**
I have it running in docker, with the command --no-cleanup. Thought that would do the trick, but it isn't. Is there somewhere a setting to disable this? Or somewhere else to change that?

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

**Please run `stf doctor` and paste the output here.**

**Comment by denis99999** [comment]
@your-it , try `--no-screen-reset` or `--screen-reset false` option!

**Comment by your-it** [comment]
Works, thanks! <3
