### ISSUE TITLE
Regression errors on bluetooth features !

### ISSUE THREAD

**Issue by denis99999** [DeviceFarmer/stf#782]
@jupe, you have recently sent PR #757 & #758 & #765 related to bluetooth features, but it seems there are regression errors with some Android SDK level, see following log errors, can you investigate about that and bring correction please ?

**Mobile HUAWEI HWANA OS-10 SDK-29:**
May 23 14:08:42 LAN-Z1-R3 docker[601]: 2024-05-23T13:08:42.467Z DBG/device:resources:service 23 [VWS0220521002017] output of granting permissions to STFService:
May 23 14:08:42 LAN-Z1-R3 docker[601]: Exception occurred while executing:
May 23 14:08:42 LAN-Z1-R3 docker[601]: **java.lang.IllegalArgumentException: Unknown permission: android.permission.BLUETOOTH_CONNECT**
May 23 14:08:42 LAN-Z1-R3 docker[601]:         at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:2382)
May 23 14:08:42 LAN-Z1-R3 docker[601]:         at com.android.server.pm.permission.PermissionManagerService.access$1500(PermissionManagerService.java:132)
May 23 14:08:42 LAN-Z1-R3 docker[601]:         at com.android.server.pm.permission.PermissionManagerService$PermissionManagerServiceInternalImpl.grantRuntimePermission(PermissionManagerService.java:3458)
May 23 14:08:42 LAN-Z1-R3 docker[601]:         at com.android.server.pm.PackageManagerService.grantRuntimePermission(PackageManagerService.java:6855)
May 23 14:08:42 LAN-Z1-R3 docker[601]:         at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:2014)
May 23 14:08:42 LAN-Z1-R3 docker[601]:         at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:248)
May 23 14:08:42 LAN-Z1-R3 docker[601]:         at android.os.ShellCommand.exec(ShellCommand.java:104)
May 23 14:08:42 LAN-Z1-R3 docker[601]:         at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:25434)
May 23 14:08:42 LAN-Z1-R3 docker[601]:         at android.os.Binder.shellCommand(Binder.java:888)
May 23 14:08:42 LAN-Z1-R3 docker[601]:         at android.os.Binder.onTransact(Binder.java:772)
May 23 14:08:42 LAN-Z1-R3 docker[601]:         at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4858)
May 23 14:08:42 LAN-Z1-R3 docker[601]:         at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4924)
May 23 14:08:42 LAN-Z1-R3 docker[601]:         at com.android.server.pm.HwPackageManagerService.onTransact(HwPackageManagerService.java:472)
May 23 14:08:42 LAN-Z1-R3 docker[601]:         at android.os.Binder.execTransactInternal(Binder.java:1028)
May 23 14:08:42 LAN-Z1-R3 docker[601]:         at android.os.Binder.execTransact(Binder.java:1001)

**Mobile HUAWEI P9 OS-6.0 SDK-23:**
May 23 14:08:53 LAN-Z1-R3 docker[601]: 2024-05-23T13:08:53.498Z DBG/device:resources:service 17 [MWS0217105006416] output of granting permissions to STFService: Bad argument: java.lang.IllegalArgumentException: **Unknown permission: android.permission.BLUETOOTH_CONNECT**
May 23 14:08:53 LAN-Z1-R3 docker[601]: usage: pm list packages [-f] [-d] [-e] [-s] [-3] [-i] [-u] [--user USER_ID] [FILTER]
May 23 14:08:53 LAN-Z1-R3 docker[601]:        pm list permission-groups
May 23 14:08:53 LAN-Z1-R3 docker[601]:        pm list permissions [-g] [-f] [-d] [-u] [GROUP]
May 23 14:08:53 LAN-Z1-R3 docker[601]:        pm list instrumentation [-f] [TARGET-PACKAGE]
May 23 14:08:53 LAN-Z1-R3 docker[601]:        pm list features
May 23 14:08:53 LAN-Z1-R3 docker[601]:        pm list libraries
May 23 14:08:53 LAN-Z1-R3 docker[601]:        pm list users
May 23 14:08:53 LAN-Z1-R3 docker[601]:        pm path PACKAGE
May 23 14:08:53 LAN-Z1-R3 docker[601]:        pm dump PACKAGE
May 23 14:08:53 LAN-Z1-R3 docker[601]:        pm install [-lrtsfd] [-i PACKAGE] [--user USER_ID] [PATH]
May 23 14:08:53 LAN-Z1-R3 docker[601]:        pm install-create [-lrtsfdp] [-i PACKAGE] [-S BYTES]
May 23 14:08:53 LAN-Z1-R3 docker[601]:                [--install-location 0/1/2]
May 23 14:08:53 LAN-Z1-R3 docker[601]:                [--force-uuid internal|UUID]
May 23 14:08:53 LAN-Z1-R3 docker[601]:        pm install-write [-S BYTES] SESSION_ID SPLIT_NAME [PATH]
May 23 14:08:53 LAN-Z1-R3 docker[601]:        pm install-commit SESSION_ID
May 23 14:08:53 LAN-Z1-R3 docker[601]:        pm install-abandon SESSION_ID
May 23 14:08:53 LAN-Z1-R3 docker[601]:        pm uninstall [-k] [--user USER_ID] PACKAGE
May 23 14:08:53 LAN-Z1-R3 docker[601]:        pm set-installer PACKAGE INSTALLER
May 23 14:08:53 LAN-Z1-R3 docker[601]:        pm move-package PACKAGE [internal|UUID]
May 23 14:08:53 LAN-Z1-R3 docker[601]:        pm move-primary-storage [internal|UUID]
May 23 14:08:53 LAN-Z1-R3 docker[601]:        pm clear [--user USER_ID] PACKAGE
May 23 14:08:53 LAN-Z1-R3 docker[601]:        pm enable [--user USER_ID] PACKAGE_OR_COMPONENT
May 23 14:08:53 LAN-Z1-R3 docker[601]:        pm disable [--user USER_ID] PACKAGE_OR_COMPONENT
May 23 14:08:53 LAN-Z1-R3 docker[601]:        pm disable-user [--user USER_ID] PACKAGE_OR_COMPONENT
May 23 14:08:53 LAN-Z1-R3 docker[601]:        pm disable-until-used [--user USER_ID] PACKAGE_OR_COMPONENT
May 23 14:08:53 LAN-Z1-R3 docker[601]:        pm hide [--user USER_ID] PACKAGE_OR_COMPONENT
May 23 14:08:53 LAN-Z1-R3 docker[601]:        pm unhide [--user USER_ID] PACKAGE_OR_COMPONENT
May 23 14:08:53 LAN-Z1-R3 docker[601]:        pm grant [--user USER_ID] PACKAGE PERMISSION
May 23 14:08:53 LAN-Z1-R3 docker[601]:        pm revoke [--user USER_ID] PACKAGE PERMISSION
May 23 14:08:53 LAN-Z1-R3 docker[601]:        pm reset-permissions
May 23 14:08:53 LAN-Z1-R3 docker[601]:        pm set-app-link [--user USER_ID] PACKAGE {always|ask|never|undefined}
May 23 14:08:53 LAN-Z1-R3 docker[601]:        pm get-app-link [--user USER_ID] PACKAGE
May 23 14:08:53 LAN-Z1-R3 docker[601]:        pm set-install-location [0/auto] [1/internal] [2/external]
May 23 14:08:53 LAN-Z1-R3 docker[601]:        pm get-install-location
May 23 14:08:53 LAN-Z1-R3 docker[601]:        pm set-permission-enforced PERMISSION [true|false]
May 23 14:08:53 LAN-Z1-R3 docker[601]:        pm trim-caches DESIRED_FREE_SPACE [internal|UUID]
May 23 14:08:53 LAN-Z1-R3 docker[601]:        pm create-user [--profileOf USER_ID] [--managed] USER_NAME
May 23 14:08:53 LAN-Z1-R3 docker[601]:        pm remove-user USER_ID
May 23 14:08:53 LAN-Z1-R3 docker[601]:        pm get-max-users
May 23 14:08:53 LAN-Z1-R3 docker[601]: [1B blob data]
May 23 14:08:53 LAN-Z1-R3 docker[601]: pm list packages: prints all packages, optionally only
May 23 14:08:53 LAN-Z1-R3 docker[601]:   those whose package name contains the text in FILTER.  Options:
May 23 14:08:53 LAN-Z1-R3 docker[601]:     -f: see their associated file.
May 23 14:08:53 LAN-Z1-R3 docker[601]:     -d: filter to only show disbled packages.
May 23 14:08:53 LAN-Z1-R3 docker[601]:     -e: filter to only show enabled packages.
May 23 14:08:53 LAN-Z1-R3 docker[601]:     -s: filter to only show system packages.
May 23 14:08:53 LAN-Z1-R3 docker[601]:     -3: filter to only show third party packages.
May 23 14:08:53 LAN-Z1-R3 docker[601]:     -i: see the installer for the packages.
May 23 14:08:53 LAN-Z1-R3 docker[601]:     -u: also include uninstalled packages.
May 23 14:08:53 LAN-Z1-R3 docker[601]: [1B blob data]
May 23 14:08:53 LAN-Z1-R3 docker[601]: pm list permission-groups: prints all known permission groups.
May 23 14:08:53 LAN-Z1-R3 docker[601]: [1B blob data]
May 23 14:08:53 LAN-Z1-R3 docker[601]: pm list permissions: prints all known permissions, optionally only
May 23 14:08:53 LAN-Z1-R3 docker[601]:   those in GROUP.  Options:
May 23 14:08:53 LAN-Z1-R3 docker[601]:     -g: organize by group.
May 23 14:08:53 LAN-Z1-R3 docker[601]:     -f: print all information.
May 23 14:08:53 LAN-Z1-R3 docker[601]:     -s: short summary.
May 23 14:08:53 LAN-Z1-R3 docker[601]:     -d: only list dangerous permissions.
May 23 14:08:53 LAN-Z1-R3 docker[601]:     -u: list only the permissions users will see.
May 23 14:08:53 LAN-Z1-R3 docker[601]: [1B blob data]
May 23 14:08:53 LAN-Z1-R3 docker[601]: pm list instrumentation: use to list all test packages; optionally
May 23 14:08:53 LAN-Z1-R3 docker[601]:   supply <TARGET-PACKAGE> to list the test packages for a particular
May 23 14:08:53 LAN-Z1-R3 docker[601]:   application.  Options:
May 23 14:08:53 LAN-Z1-R3 docker[601]:     -f: list the .apk file for the test package.
May 23 14:08:53 LAN-Z1-R3 docker[601]: [1B blob data]
May 23 14:08:53 LAN-Z1-R3 docker[601]: pm list features: prints all features of the system.
May 23 14:08:53 LAN-Z1-R3 docker[601]: [1B blob data]
May 23 14:08:53 LAN-Z1-R3 docker[601]: pm list users: prints all users on the system.
May 23 14:08:53 LAN-Z1-R3 docker[601]: [1B blob data]
May 23 14:08:53 LAN-Z1-R3 docker[601]: pm path: print the path to the .apk of the given PACKAGE.
May 23 14:08:53 LAN-Z1-R3 docker[601]: [1B blob data]
May 23 14:08:53 LAN-Z1-R3 docker[601]: pm dump: print system state associated with the given PACKAGE.
May 23 14:08:53 LAN-Z1-R3 docker[601]: [1B blob data]
May 23 14:08:53 LAN-Z1-R3 docker[601]: pm install: install a single legacy package
May 23 14:08:53 LAN-Z1-R3 docker[601]: pm install-create: create an install session
May 23 14:08:53 LAN-Z1-R3 docker[601]:     -l: forward lock application
May 23 14:08:53 LAN-Z1-R3 docker[601]:     -r: replace existing application
May 23 14:08:53 LAN-Z1-R3 docker[601]:     -t: allow test packages
May 23 14:08:53 LAN-Z1-R3 docker[601]:     -i: specify the installer package name
May 23 14:08:53 LAN-Z1-R3 docker[601]:     -s: install application on sdcard
May 23 14:08:53 LAN-Z1-R3 docker[601]:     -f: install application on internal flash
May 23 14:08:53 LAN-Z1-R3 docker[601]:     -d: allow version code downgrade
May 23 14:08:53 LAN-Z1-R3 docker[601]:     -p: partial application install
May 23 14:08:53 LAN-Z1-R3 docker[601]:     -g: grant all runtime permissions
May 23 14:08:53 LAN-Z1-R3 docker[601]:     -S: size in bytes of entire session
May 23 14:08:53 LAN-Z1-R3 docker[601]: [1B blob data]
May 23 14:08:53 LAN-Z1-R3 docker[601]: pm install-write: write a package into existing session; path may
May 23 14:08:53 LAN-Z1-R3 docker[601]:   be '-' to read from stdin
May 23 14:08:53 LAN-Z1-R3 docker[601]:     -S: size in bytes of package, required for stdin
May 23 14:08:53 LAN-Z1-R3 docker[601]: [1B blob data]
May 23 14:08:53 LAN-Z1-R3 docker[601]: pm install-commit: perform install of fully staged session
May 23 14:08:53 LAN-Z1-R3 docker[601]: pm install-abandon: abandon session
May 23 14:08:53 LAN-Z1-R3 docker[601]: [1B blob data]
May 23 14:08:53 LAN-Z1-R3 docker[601]: pm set-installer: set installer package name
May 23 14:08:53 LAN-Z1-R3 docker[601]: [1B blob data]
May 23 14:08:53 LAN-Z1-R3 docker[601]: pm uninstall: removes a package from the system. Options:
May 23 14:08:53 LAN-Z1-R3 docker[601]:     -k: keep the data and cache directories around after package removal.
May 23 14:08:53 LAN-Z1-R3 docker[601]: [1B blob data]
May 23 14:08:53 LAN-Z1-R3 docker[601]: pm clear: deletes all data associated with a package.
May 23 14:08:53 LAN-Z1-R3 docker[601]: [1B blob data]
May 23 14:08:53 LAN-Z1-R3 docker[601]: pm enable, disable, disable-user, disable-until-used: these commands
May 23 14:08:53 LAN-Z1-R3 docker[601]:   change the enabled state of a given package or component (written
May 23 14:08:53 LAN-Z1-R3 docker[601]:   as "package/class").
May 23 14:08:53 LAN-Z1-R3 docker[601]: [1B blob data]
May 23 14:08:53 LAN-Z1-R3 docker[601]: pm grant, revoke: these commands either grant or revoke permissions
May 23 14:08:53 LAN-Z1-R3 docker[601]:     to apps. The permissions must be declared as used in the app's
May 23 14:08:53 LAN-Z1-R3 docker[601]:     manifest, be runtime permissions (protection level dangerous),
May 23 14:08:53 LAN-Z1-R3 docker[601]:     and the app targeting SDK greater than Lollipop MR1.
May 23 14:08:53 LAN-Z1-R3 docker[601]: [1B blob data]
May 23 14:08:53 LAN-Z1-R3 docker[601]: pm reset-permissions: revert all runtime permissions to their default state.
May 23 14:08:53 LAN-Z1-R3 docker[601]: [1B blob data]
May 23 14:08:53 LAN-Z1-R3 docker[601]: pm get-install-location: returns the current install location.
May 23 14:08:53 LAN-Z1-R3 docker[601]:     0 [auto]: Let system decide the best location
May 23 14:08:53 LAN-Z1-R3 docker[601]:     1 [internal]: Install on internal device storage
May 23 14:08:53 LAN-Z1-R3 docker[601]:     2 [external]: Install on external media
May 23 14:08:53 LAN-Z1-R3 docker[601]: [1B blob data]
May 23 14:08:53 LAN-Z1-R3 docker[601]: pm set-install-location: changes the default install location.
May 23 14:08:53 LAN-Z1-R3 docker[601]:   NOTE: this is only intended for debugging; using this can cause
May 23 14:08:53 LAN-Z1-R3 docker[601]:   applications to break and other undersireable behavior.
May 23 14:08:53 LAN-Z1-R3 docker[601]:     0 [auto]: Let system decide the best location
May 23 14:08:53 LAN-Z1-R3 docker[601]:     1 [internal]: Install on internal device storage
May 23 14:08:53 LAN-Z1-R3 docker[601]:     2 [external]: Install on external media
May 23 14:08:53 LAN-Z1-R3 docker[601]: [1B blob data]
May 23 14:08:53 LAN-Z1-R3 docker[601]: pm trim-caches: trim cache files to reach the given free space.
May 23 14:08:53 LAN-Z1-R3 docker[601]: [1B blob data]
May 23 14:08:53 LAN-Z1-R3 docker[601]: pm create-user: create a new user with the given USER_NAME,
May 23 14:08:53 LAN-Z1-R3 docker[601]:   printing the new user identifier of the user.
May 23 14:08:53 LAN-Z1-R3 docker[601]: [1B blob data]
May 23 14:08:53 LAN-Z1-R3 docker[601]: pm remove-user: remove the user with the given USER_IDENTIFIER,
May 23 14:08:53 LAN-Z1-R3 docker[601]:   deleting all data associated with that user
May 23 14:08:53 LAN-Z1-R3 docker[601]: [1B blob data]

**Comment by jupe** [comment]
> `Unknown permission: android.permission.BLUETOOTH_CONNECT`

ouch, obviously these permission changes causes trouple with some devices 😖  Have to think of to handle this right way.

**Comment by dlhace** [comment]
Was this ever resolved?  my stf-provider keeps stopping and this is the only error message I am seeing.

**Comment by jupe** [comment]
Unfortunately haven’t had time for this. So you have some android 10 and 6 phones that didn’t work? Have you tried other SDK:s? I might have some old phones to try out.

as a workaround you could stick on old stfservice..

**Comment by denis99999** [comment]
@jupe , you can't react like that, in fact when you introduce a new feature you have to make sure that the whole thing doesn't regress, because otherwise it's the whole community that you potentially impact, so it seems to me that either you find the time to fix the bug you introduced, or maybe you should consider going back and removing your Bluetooth functionality, what do you think @koral-- ?

**Comment by jupe** [comment]
In my experience, regressions happen without comprehensive CI that prevents it, no matter how skilled developers are making the software. I don't want to start complaining, instead finding solutions.

Anyway, obviously https://github.com/DeviceFarmer/stf/pull/765/files#diff-584081c1dc4de1decf9b40accd14d727f4d1a93ef0a2263b11a25e4f9eb596d3R101 is the culprits. Have to figure out way which are compatible with all SDKs. Any idea? We can revert #765 until solution is found. I think it just prevent those new BLE feature working, but shouldn't cause other harm. I doubt I don't have phone that reproduce issue. Can it be reproduced with simulator ?

By the way, SDK-23 is not even supported by [README](https://github.com/DeviceFarmer/stf?tab=readme-ov-file#features). Should we still support android 6 really? We should update README as well about supported SDK's.

**Comment by denis99999** [comment]
@jupe , yes in the code I think it is enough to make a switch on the SDK level (>= 30 or 31 I think) to call or not the `setPermission` function, you do not a priori in this case need phones with SDKs lower to ensure a priori that it works although it is indeed better, but it cannot be worse than currently.
The README is not up to date, it's true, that's not why you have to modify the code accordingly as you want.
Yes, backward compatibility must be maintained as much as possible.

**Comment by jupe** [comment]
During #765, I tested one phone with SDK-28 successfully while tried to find compatible solution. Obviously it didn't work for certain phones/SDK unfortunately. Feel free to complain, but it won't help cooperation. 

Instead SDK level switch, it could be also try-ignore solution with logs. At least it ensure those functionality as many phones as possible but allow to use phones that won't support these permissions. Thoughts?

**Comment by jupe** [comment]
something like this should tackle this case I guess: https://github.com/embedded-community/stf/commit/595bf2086a398cb262ecd18057861cc1d7dda21c . Have to try out with different phones.

**Comment by denis99999** [comment]
@jupe , I have some old phones, I will also do some tests on your next PR to complete your tests!

**Comment by jupe** [comment]
Free to review and try: https://github.com/DeviceFarmer/stf/pull/804
Not tested yet with older models.
