### ISSUE TITLE
How settings for only monitoring the device

### ISSUE THREAD

**Issue by pbezpal** [DeviceFarmer/stf#801]
Hello! Are there settings for only monitoring the device?

**Comment by jupe** [comment]
I don't think there is such option at the moment, but indeed it would be useful feature.

**Comment by denis99999** [comment]
@pbezpal , can you describe more clearly your request please because I did not really understand it?

**Comment by pbezpal** [comment]
@denis99999 we connected the server on which the autotest environment is configured to STF via appium. To avoid being able to connect to the device and manipulate it during tests, we want to know if there is a possibility to configure STF for a certain provider only monitoring. Hope that clearly described the situation)

**Comment by denis99999** [comment]
@pbezpal , no there is not this possibility of prohibiting interaction with a device under control, it is up to the human to decide not to interact with it, but this seems natural since only the same user can open one or multiple video streams on a device under control

**Comment by pbezpal** [comment]
Thanks
