### ISSUE TITLE
How to check the version of OpenSTF?

### ISSUE THREAD

**Issue by barrypradhan** [DeviceFarmer/stf#94]
**What is the issue or idea you have?**
I'm unable to check the STF version currently I am using.

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

**Please provide the steps to reproduce the issue.**
I installed the STF by pulling the docker from **docker pull devicefarmer/stf** and working fine.
I just want to know how to know the version of running STF.
The command **stf -version** doesn't work.

**What is the expected behavior?**

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

**Please run `stf doctor` and paste the output here.**

**Comment by denis99999** [comment]
@barrypradhan , you have to run the command `stf --version` or` stf -V`, run `stf --help` or `stf -h` for help

**Comment by barrypradhan** [comment]
I get this when i try **stf --version** , **stf -V**  or **stf --help** ,  **stf -h**

_Command 'stf' not found, did you mean:

  command 'std' from snap std (0.0.7)
  command 'gtf' from deb xserver-xorg-core
  command 'tf' from deb tf
  command 'tf' from deb tf5
  command 'sdf' from deb sdf
  command 'stl' from deb numpy-stl
  command 'stg' from deb stgit
  command 'wtf' from deb bsdgames
  command 'sf' from deb ruby-sprite-factory
  command 'syf' from deb alliance

See 'snap info <snapname>' for additional versions._

**Comment by denis99999** [comment]
`docker run --rm devicefarmer/stf:latest stf --version`

**Comment by barrypradhan** [comment]
many thanks @denis99999 , i can check the version now.

its **3.4.3**. 
Is this the latest version?

**Comment by denis99999** [comment]
yes

**Comment by barrypradhan** [comment]
great. thank you!
