### ISSUE TITLE
MI9 failed to show the screen after click the `use`

### ISSUE THREAD

**Issue by chaooe** [DeviceFarmer/stf#99]
Device: MI9
SDK: 29

STF version: devicefarmer/stf:latest

STF logs as below:
android-provider2_1     | 2020-09-09T01:28:33.904Z IMP/device:plugins:group 13 [35fbffe7] Now owned by "administrator@fakedomain.com"
android-provider2_1     | 2020-09-09T01:28:33.906Z INF/device:plugins:group 13 [35fbffe7] Subscribing to group channel "T9qTVtveQzSknyebPA78wQ=="
android-provider2_1     | 2020-09-09T01:28:33.998Z INF/device:plugins:screen:stream 13 [35fbffe7] Setting frame producer projection to 645x846
android-provider2_1     | 2020-09-09T01:28:34.001Z INF/device:plugins:screen:stream 13 [35fbffe7] Requesting frame producer to start
nginx_1                 | 10.0.2.2 - - [09/Sep/2020:01:28:34 +0000] "GET /static/app/browsers/icon/36x36/android-browser.png HTTP/1.1" 200 3358 "http://192.168.33.100/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:80.0) Gecko/20100101 Firefox/80.0"
nginx_1                 | 10.0.2.2 - - [09/Sep/2020:01:28:34 +0000] "GET /static/app/browsers/icon/36x36/chrome.png HTTP/1.1" 200 2388 "http://192.168.33.100/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:80.0) Gecko/20100101 Firefox/80.0"
android-provider2_1     | 2020-09-09T01:28:34.005Z INF/device:plugins:screen:stream 13 [35fbffe7] Launching screen service
android-provider2_1     | 2020-09-09T01:28:34.044Z INF/device:plugins:connect 13 [35fbffe7] Listening on port 7451
android-provider2_1     | 2020-09-09T01:28:34.048Z IMP/device:plugins:connect 13 [35fbffe7] Remote Connect Started for device "35fbffe7" at "192.168.33.100:7451"
android-provider2_1     | 2020-09-09T01:28:34.052Z INF/device:plugins:screen:stream 13 [35fbffe7] minicap says: "PID: 11806"
android-provider2_1     | 2020-09-09T01:28:34.054Z INF/device:plugins:screen:stream 13 [35fbffe7] minicap says: "INFO: Using projection 1080x2340@390x846/0"
android-provider2_1     | 2020-09-09T01:28:34.055Z INF/device:plugins:screen:stream 13 [35fbffe7] minicap says: "INFO: (external/MY_minicap/src/minicap_29.cpp:241) Creating SurfaceComposerClient"
android-provider2_1     | 2020-09-09T01:28:34.057Z INF/device:plugins:screen:stream 13 [35fbffe7] minicap says: "INFO: (external/MY_minicap/src/minicap_29.cpp:244) Performing SurfaceComposerClient init check"
android-provider2_1     | 2020-09-09T01:28:34.058Z INF/device:plugins:screen:stream 13 [35fbffe7] minicap says: "INFO: (external/MY_minicap/src/minicap_29.cpp:255) Creating virtual display"
android-provider2_1     | 2020-09-09T01:28:34.059Z INF/device:plugins:screen:stream 13 [35fbffe7] minicap says: "INFO: (external/MY_minicap/src/minicap_29.cpp:261) Creating buffer queue"
android-provider2_1     | 2020-09-09T01:28:34.061Z INF/device:plugins:screen:stream 13 [35fbffe7] minicap says: "INFO: (external/MY_minicap/src/minicap_29.cpp:264) Setting buffer options"
android-provider2_1     | 2020-09-09T01:28:34.062Z INF/device:plugins:screen:stream 13 [35fbffe7] minicap says: "INFO: (external/MY_minicap/src/minicap_29.cpp:268) Creating CPU consumer"
android-provider2_1     | 2020-09-09T01:28:34.064Z INF/device:plugins:screen:stream 13 [35fbffe7] minicap says: "INFO: (external/MY_minicap/src/minicap_29.cpp:272) Creating frame waiter"
android-provider2_1     | 2020-09-09T01:28:34.071Z INF/device:plugins:screen:stream 13 [35fbffe7] minicap says: "INFO: (external/MY_minicap/src/minicap_29.cpp:276) Publishing virtual display"
android-provider2_1     | 2020-09-09T01:28:34.073Z INF/device:plugins:screen:stream 13 [35fbffe7] minicap says: "Vector<> have different types (this=0x7fca0f0de0, rhs=0x7fca0f0f30)"
android-provider2_1     | 2020-09-09T01:28:34.075Z INF/device:plugins:screen:stream 13 [35fbffe7] Connecting to minicap service
android-provider2_1     | 2020-09-09T01:28:34.081Z INF/device:plugins:connect 13 [35fbffe7] New remote ADB connection from ::ffff:10.0.2.2
android-provider2_1     | 2020-09-09T01:28:34.100Z WRN/device:plugins:screen:stream 13 [35fbffe7] Shell keeping minicap running ended unexpectedly
android-provider2_1     | 2020-09-09T01:28:35.619Z INF/device:plugins:screen:stream 13 [35fbffe7] Disconnecting from minicap service
android-provider2_1     | 2020-09-09T01:28:35.622Z INF/device:plugins:screen:stream 13 [35fbffe7] Stopping minicap service
android-provider2_1     | 2020-09-09T01:28:35.623Z FTL/device:plugins:screen:stream 13 [35fbffe7] Frame producer had an error FailError: Failure: 'closed'
android-provider2_1     |     at /app/node_modules/@devicefarmer/adbkit/lib/adb/parser.js:183:29
android-provider2_1     |     at runCallback (timers.js:789:20)
android-provider2_1     |     at tryOnImmediate (timers.js:751:5)
android-provider2_1     |     at processImmediate [as _immediateCallback] (timers.js:722:5)
android-provider2_1     | 2020-09-09T01:28:35.625Z FTL/util:lifecycle 13 [35fbffe7] Shutting down due to fatal error
android-provider2_1     | 2020-09-09T01:28:35.634Z INF/provider 1 [*] Cleaning up device worker "35fbffe7"
android-provider2_1     | 2020-09-09T01:28:35.635Z ERR/provider 1 [*] Device worker "35fbffe7" died with code 1
android-provider2_1     | 2020-09-09T01:28:35.635Z INF/provider 1 [*] Restarting device worker "35fbffe7"
android-provider2_1     | 2020-09-09T01:28:36.443Z INF/device:support:push 49 [35fbffe7] Sending output to "tcp://dev-triproxy:7270"
android-provider2_1     | 2020-09-09T01:28:36.447Z INF/device 49 [35fbffe7] Preparing device
android-provider2_1     | 2020-09-09T01:28:36.958Z INF/device:support:sub 49 [35fbffe7] Receiving input from "tcp://dev-triproxy:7250"
android-provider2_1     | 2020-09-09T01:28:36.961Z INF/device:support:sub 49 [35fbffe7] Subscribing to permanent channel "*ALL"
android-provider2_1     | 2020-09-09T01:28:37.012Z INF/device:support:properties 49 [35fbffe7] Loading properties
android-provider2_1     | 2020-09-09T01:28:37.045Z INF/device:support:sdk 49 [35fbffe7] Supports SDK 29
android-provider2_1     | 2020-09-09T01:28:37.047Z INF/device:support:abi 49 [35fbffe7] Supports ABIs arm64-v8a, armeabi-v7a, armeabi
android-provider2_1     | 2020-09-09T01:28:37.187Z INF/device:resources:minicap 49 [35fbffe7] Installing "/app/node_modules/@devicefarmer/minicap-prebuilt/prebuilt/arm64-v8a/bin/minicap" as "/data/local/tmp/minicap"
android-provider2_1     | 2020-09-09T01:28:37.188Z INF/device:resources:minicap 49 [35fbffe7] Installing "/app/node_modules/@devicefarmer/minicap-prebuilt/prebuilt/arm64-v8a/lib/android-29/minicap.so" as "/data/local/tmp/minicap.so"
android-provider2_1     | 2020-09-09T01:28:37.270Z INF/device:resources:service 49 [35fbffe7] Checking whether we need to install STFService
android-provider2_1     | 2020-09-09T01:28:37.315Z INF/device:resources:service 49 [35fbffe7] Running version check
android-provider2_1     | 2020-09-09T01:28:37.551Z INF/device:resources:service 49 [35fbffe7] STFService up to date
android-provider2_1     | 2020-09-09T01:28:37.556Z INF/device:plugins:service 49 [35fbffe7] Launching agent
android-provider2_1     | 2020-09-09T01:28:37.883Z INF/device:plugins:service 49 [35fbffe7] Agent says: "Starting minitouch agent"
android-provider2_1     | 2020-09-09T01:28:37.901Z INF/device:plugins:service 49 [35fbffe7] Agent says: "Listening on @stfagent"
android-provider2_1     | 2020-09-09T01:28:37.915Z INF/device:plugins:service 49 [35fbffe7] Launching service
android-provider2_1     | 2020-09-09T01:28:37.916Z INF/device:plugins:service 49 [35fbffe7] using 'start-foreground-service' command for API 29
android-provider2_1     | 2020-09-09T01:28:37.918Z INF/device:plugins:service 49 [35fbffe7] Agent says: "InputClient started"
android-provider2_1     | 2020-09-09T01:28:37.967Z INF/device:plugins:display 49 [35fbffe7] Reading display info
android-provider2_1     | 2020-09-09T01:28:37.982Z INF/device:plugins:phone 49 [35fbffe7] Fetching phone info
android-provider2_1     | 2020-09-09T01:28:37.996Z INF/device:plugins:identity 49 [35fbffe7] Solving identity
android-provider2_1     | 2020-09-09T01:28:38.004Z INF/device:plugins:solo 49 [35fbffe7] Subscribing to permanent channel "dXV5c4EV96KRZMyT48Lo17Vv3Dg="
android-provider2_1     | 2020-09-09T01:28:38.006Z INF/device:plugins:screen:stream 49 [35fbffe7] Starting WebSocket server on port 7462
android-provider2_1     | 2020-09-09T01:28:38.135Z INF/device:resources:minitouch 49 [35fbffe7] Installing "/app/node_modules/@devicefarmer/minitouch-prebuilt/prebuilt/arm64-v8a/bin/minitouch" as "/data/local/tmp/minitouch"
android-provider2_1     | 2020-09-09T01:28:38.175Z WRN/device:plugins:data 49 [35fbffe7] Unable to find device data { serial: '35fbffe7',
android-provider2_1     |   platform: 'Android',
android-provider2_1     |   manufacturer: 'XIAOMI',
android-provider2_1     |   operator: null,
android-provider2_1     |   model: 'MI 9',
android-provider2_1     |   version: '10',
android-provider2_1     |   abi: 'arm64-v8a',
android-provider2_1     |   sdk: '29',
android-provider2_1     |   product: 'cepheus',
android-provider2_1     |   cpuPlatform: 'msmnile',
android-provider2_1     |   openGLESVersion: '3.2',
android-provider2_1     |   marketName: 'MI 9',
android-provider2_1     |   display: 
android-provider2_1     |    { id: 0,
android-provider2_1     |      width: 1080,
android-provider2_1     |      height: 2340,
android-provider2_1     |      xdpi: 403.4110107421875,
android-provider2_1     |      ydpi: 404.32598876953125,
android-provider2_1     |      fps: 60.000003814697266,
android-provider2_1     |      density: 2.75,
android-provider2_1     |      rotation: 0,
android-provider2_1     |      secure: true,
android-provider2_1     |      size: 6.37662511715682,
android-provider2_1     |      url: 'ws://192.168.33.100:7462' },
android-provider2_1     |   phone: { network: 'UNKNOWN' } }
android-provider2_1     | 2020-09-09T01:28:38.181Z INF/device:plugins:touch 49 [35fbffe7] Touch origin is top left
android-provider2_1     | 2020-09-09T01:28:38.182Z INF/device:plugins:touch 49 [35fbffe7] Requesting touch consumer to start
android-provider2_1     | 2020-09-09T01:28:38.184Z INF/device:plugins:touch 49 [35fbffe7] Launching touch service
android-provider2_1     | 2020-09-09T01:28:38.200Z INF/device:plugins:touch 49 [35fbffe7] Connecting to minitouch service
android-provider2_1     | 2020-09-09T01:28:38.209Z INF/device:plugins:touch 49 [35fbffe7] minitouch says: "open: Permission denied"
android-provider2_1     | 2020-09-09T01:28:38.211Z INF/device:plugins:touch 49 [35fbffe7] minitouch says: "Unable to open device /dev/input/event7 for inspectionopen: Permission denied"
android-provider2_1     | 2020-09-09T01:28:38.214Z INF/device:plugins:touch 49 [35fbffe7] minitouch says: "Unable to open device /dev/input/event6 for inspectionopen: Permission denied"
android-provider2_1     | 2020-09-09T01:28:38.215Z INF/device:plugins:touch 49 [35fbffe7] minitouch says: "Unable to open device /dev/input/event5 for inspectionopen: Permission denied"
android-provider2_1     | 2020-09-09T01:28:38.216Z INF/device:plugins:touch 49 [35fbffe7] minitouch says: "Unable to open device /dev/input/event3 for inspectionopen: Permission denied"
android-provider2_1     | 2020-09-09T01:28:38.218Z INF/device:plugins:touch 49 [35fbffe7] minitouch says: "Unable to open device /dev/input/event0 for inspectionopen: Permission denied"
android-provider2_1     | 2020-09-09T01:28:38.219Z INF/device:plugins:touch 49 [35fbffe7] minitouch says: "Unable to open device /dev/input/event1 for inspectionopen: Permission denied"
android-provider2_1     | 2020-09-09T01:28:38.221Z INF/device:plugins:touch 49 [35fbffe7] minitouch says: "Unable to open device /dev/input/event2 for inspectionopen: Permission denied"
android-provider2_1     | 2020-09-09T01:28:38.222Z INF/device:plugins:touch 49 [35fbffe7] minitouch says: "Unable to open device /dev/input/event4 for inspectionUnable to find a suitable touch device"
android-provider2_1     | 2020-09-09T01:28:38.223Z INF/device:plugins:touch 49 [35fbffe7] minitouch says: "using Android InputManager"
android-provider2_1     | 2020-09-09T01:28:38.316Z INF/device:plugins:touch 49 [35fbffe7] Reading minitouch banner
android-provider2_1     | 2020-09-09T01:28:38.319Z INF/device:plugins:touch 49 [35fbffe7] minitouch says: "Connection established"
android-provider2_1     | 2020-09-09T01:28:38.323Z INF/device:plugins:vnc 49 [35fbffe7] Starting VNC server on port 7464
android-provider2_1     | 2020-09-09T01:28:38.326Z INF/device:plugins:browser 49 [35fbffe7] Loading browser list
android-provider2_1     | 2020-09-09T01:28:38.336Z INF/device:plugins:browser 49 [35fbffe7] Updating browser list
android-provider2_1     | 2020-09-09T01:28:38.337Z WRN/device:plugins:browser 49 [35fbffe7] Unmapped browser "com.alibaba.android.rimet"
android-provider2_1     | 2020-09-09T01:28:38.339Z WRN/device:plugins:browser 49 [35fbffe7] Unmapped browser "com.baidu.haokan"
android-provider2_1     | 2020-09-09T01:28:38.340Z WRN/device:plugins:browser 49 [35fbffe7] Unmapped browser "com.baidu.searchbox"
android-provider2_1     | 2020-09-09T01:28:38.341Z WRN/device:plugins:browser 49 [35fbffe7] Unmapped browser "com.sina.weibo"
android-provider2_1     | 2020-09-09T01:28:38.347Z INF/device:plugins:mute 49 [35fbffe7] Will not mute master volume
android-provider2_1     | 2020-09-09T01:28:38.461Z INF/device:resources:minirev 49 [35fbffe7] Installing "/app/vendor/minirev/arm64-v8a/minirev" as "/data/local/tmp/minirev"
android-provider2_1     | 2020-09-09T01:28:38.516Z INF/device:plugins:forward 49 [35fbffe7] Launching reverse port forwarding service
android-provider2_1     | 2020-09-09T01:28:38.534Z INF/device:plugins:forward 49 [35fbffe7] Connecting to reverse port forwarding service
android-provider2_1     | 2020-09-09T01:28:38.695Z INF/device 49 [35fbffe7] Fully operational
nginx_1                 | 10.0.2.2 - - [09/Sep/2020:01:28:39 +0000] "GET /static/app/devices/icon/x120/E30HT.jpg HTTP/1.1" 200 1528 "http://192.168.33.100/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:80.0) Gecko/20100101 Firefox/80.0"

**Comment by denis99999** [comment]
@chaooe , please fill the bug report template and detail your running configuration.

**Comment by chaooe** [comment]
close it and format it by this issue link https://github.com/DeviceFarmer/stf/issues/101
